import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, ReactNode, useContext, useEffect, useState } from "react";
import * as Localization from "expo-localization";
import { secureStorage } from "../services/secureStorage";
import apiClient from "../services/api.config";

const translations = {
  fr: {
    home: 'Accueil',
    profile: 'Profil',
    appointments: 'Rendez-vous',
    notifications: 'Notifications',
    favorites: 'Favoris',
    editProfile: 'Modifier le profil',
    language: 'Langue',
    theme: 'Apparence',
    prescriptions: 'Mes Ordonnances',
    paymentMethod: 'Moyen de Paiement',
    faqs: 'FAQs',
    logout: 'Déconnexion',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    success: 'Succès',
    error: 'Erreur',
    loading: 'Chargement...',
    profileUpdated: 'Votre profil a été mis à jour avec succès !',
    languageChanged: 'La langue a été changée en',
    themeChanged: 'Le thème a été modifié avec succès',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Email',
    phone: 'Téléphone',
    address: 'Adresse',
    city: 'Ville',
    dateOfBirth: 'Date de Naissance',
    gender: 'Genre',
    bloodGroup: 'Groupe Sanguin',
    height: 'Taille (m)',
    weight: 'Poids (kg)',
    male: 'Homme',
    female: 'Femme',
    other: 'Autre',
    areYouSureLogout: 'Êtes-vous sûr de vouloir vous déconnecter ?',
    healthInfo: 'Informations de santé',
    bloodType: 'Groupe sanguin',
    age: 'Âge',
    bmi: 'Statut IMC',
    rdvCount: 'Rendez-vous',
    noNotification: 'Aucune notification',
    noNotificationSub: 'Vous n\'avez pas encore reçu de notification.',
    markAllRead: 'Tout lire',
    bestDoctors: 'Meilleurs Docteurs',
    seeAll: 'Voir tout',
    searchPlaceholder: 'Rechercher médecin, médicaments...',
    doctor: 'Docteur',
    pharmacy: 'Pharmacie',
    hospital: 'Hôpital',
    ambulance: 'Ambulance',
    bannerTitle1: 'Protection précoce pour',
    bannerTitle2: 'la santé de votre famille',
    learnMore: 'En savoir plus',
    loadingDoctors: 'Chargement des médecins...',
    retryButton: 'Réessayer',
    noDoctors: 'Aucun médecin disponible',
    cannotLoadDoctors: 'Impossible de charger les médecins',
    aptTitle: 'Rendez-vous',
    aptLoading: 'Chargement de vos rendez-vous...',
    aptPending: 'En attente',
    aptConfirmed: 'Confirmé',
    aptPast: 'Passé',
    aptRejected: 'Refusé',
    aptOnline: 'En ligne',
    aptHome: 'À domicile',
    aptHospital: 'À l\'hôpital',
    aptMoreDetails: 'Plus de détails',
    aptHideDetails: 'Masquer les détails',
    aptCall: 'Appeler',
    aptWhatsApp: 'WhatsApp',
    aptDirections: 'Itinéraire',
    aptJoinVideo: 'Rejoindre la consultation',
    aptConfirmedMsg: 'Rendez-vous confirmé',
    aptReschedule: 'Reprogrammer',
    aptDelete: 'Supprimer',
    aptEmpty: 'Aucun rendez-vous',
    aptCancelTitle: 'Annuler le rendez-vous',
    aptCancelMsg: 'Êtes-vous sûr de vouloir annuler ce rendez-vous ?',
    aptDeleteTitle: 'Supprimer le rendez-vous',
    aptDeleteMsg: 'Êtes-vous sûr de vouloir supprimer ce rendez-vous ?',
    aptCancelSuccess: 'Rendez-vous annulé avec succès',
    aptJoinTitle: 'Rejoindre la consultation',
    aptJoinMsg: 'Vous allez être redirigé vers la vidéoconférence',
    aptJoin: 'Rejoindre',
    aptErrLoad: 'Impossible de charger vos rendez-vous. Veuillez réessayer.',
    bkTitle: 'Nouveau rendez-vous',
    bkTypeTitle: 'Type de consultation',
    bkTypeSubtitle: 'Choisissez le type de consultation qui vous convient',
    bkOnline: 'Consultation en ligne',
    bkOnlineDesc: 'Consultation par vidéo',
    bkHome: 'Consultation à domicile',
    bkHomeDesc: 'Le médecin vient chez vous',
    bkHospital: 'Consultation à l\'hôpital',
    bkHospitalDesc: 'Rendez-vous en présentiel',
    bkDescLabel: 'Description du problème',
    bkDescPlaceholder: 'Décrivez brièvement votre problème de santé...',
    bkNext: 'Suivant',
    bkValidationMsg: 'Veuillez sélectionner un type et ajouter une description',
    cpTitle: 'Changer le mot de passe',
    cpInfo: 'Votre mot de passe doit contenir au moins 8 caractères',
    cpCurrent: 'Mot de passe actuel',
    cpCurrentPlaceholder: 'Entrez votre mot de passe actuel',
    cpNew: 'Nouveau mot de passe',
    cpNewPlaceholder: 'Entrez votre nouveau mot de passe',
    cpConfirm: 'Confirmer le nouveau mot de passe',
    cpConfirmPlaceholder: 'Confirmez votre nouveau mot de passe',
    cpForgot: 'Mot de passe oublié ?',
    cpWeak: 'Faible',
    cpMedium: 'Moyen',
    cpStrong: 'Fort',
    cpMatch: 'Les mots de passe correspondent',
    cpNoMatch: 'Les mots de passe ne correspondent pas',
    cpSave: 'Mettre à jour le mot de passe',
    cpSuccess: 'Votre mot de passe a été modifié avec succès',
    cpErrCurrent: 'Veuillez entrer votre mot de passe actuel',
    cpErrNew: 'Veuillez entrer un nouveau mot de passe',
    cpErrLen: 'Le mot de passe doit contenir au moins 8 caractères',
    cpErrSame: 'Le nouveau mot de passe doit être différent de l\'ancien',
    cnpTitle: 'Créer un nouveau mot de passe',
    cnpDesc: 'Créez votre nouveau mot de passe pour vous connecter',
    cnpNew: 'Nouveau mot de passe',
    cnpConfirm: 'Confirmer le mot de passe',
    cnpCreate: 'Créer le mot de passe',
    cnpSuccess: 'Vous avez réinitialisé votre mot de passe avec succès.',
    cnpErrLen: 'Le mot de passe doit contenir au moins 6 caractères',
    cnpErrMatch: 'Les mots de passe ne correspondent pas',
    cnpLogin: 'Connexion',
    ddTitle: 'Détails du médecin',
    ddLoading: 'Chargement...',
    ddRetry: 'Réessayer',
    ddAbout: 'À propos',
    ddExperience: 'ans d\'expérience',
    ddPatients: 'patients',
    ddDiplomas: 'Diplômes',
    ddPrices: 'Tarifs',
    ddAvailableDates: 'Dates disponibles',
    ddLoadingDates: 'Chargement des disponibilités...',
    ddNoDates: 'Aucune disponibilité dans les 30 prochains jours',
    ddAvailableSlots: 'Créneaux disponibles',
    ddNoSlots: 'Aucun créneau disponible pour cette date',
    ddOccupied: 'occupé',
    ddFeeDetails: 'Détails des frais',
    ddConsultation: 'Consultation',
    ddConfirmFee: 'Frais de confirmation',
    ddTotal: 'Total',
    ddNbOnline: 'Les frais de confirmation de',
    ddNbOnline2: 'FCFA ne sont pas remboursables, que le rendez-vous soit accepté ou refusé.',
    ddNbOnlineLabel: 'NB :',
    ddPayOnSite: 'Paiement sur place :',
    ddPayOnSiteMsg: 'Le paiement se fera directement lors de la consultation.',
    ddSelectDate: 'Veuillez sélectionner une date',
    ddSelectSlot: 'Veuillez sélectionner un créneau horaire',
    ddContinuePayment: 'Continuer vers le paiement',
    ddConfirmRdv: 'Confirmer le rendez-vous',
    ddSuccessMsg: 'Votre rendez-vous a été créé avec succès !',
    ddConsultOnline: 'Consultation en ligne',
    ddConsultHome: 'Consultation à domicile',
    ddConsultHospital: 'Consultation à l\'hôpital',
    ddCannotLoad: 'Impossible de charger les détails du médecin',
    ddCabinet: 'Cabinet du docteur',
    ddYourPosition: 'Votre position',
    ddUseMyLocation: 'Utiliser ma position actuelle',
    ddGettingLocation: 'Obtention de la position...',
    ddChangeLocation: 'Changer la position',
    ddIndicationLabel: 'Indication complémentaire',
    ddOptional: 'Optionnel',
    ddIndicationPlaceholder: 'Ex: Maison bleue derrière l\'église, près de la pharmacie...',
    ddNoLocationMsg: 'Si le GPS ne fonctionne pas, ajoutez une indication complémentaire pour aider le médecin à vous trouver.',
    aptOpenRoute: 'Ouvrir l\'itinéraire',
    aptShareLocation: 'Partager via WhatsApp',
    dlTitle: 'Choisir un médecin',
    dlSearchPlaceholder: 'Rechercher un médecin...',
    dlLoading: 'Chargement des médecins...',
    dlNoDoctor: 'Aucun médecin trouvé',
    dlTryOther: 'Essayez une autre recherche',
    dlNoneForType: 'Aucun médecin disponible pour',
    dlRetry: 'Réessayer',
    dlCannotLoad: 'Impossible de charger les médecins',
    epTitle: 'Modifier le Profil',
    epChangePhoto: 'Changer la photo',
    epUploading: 'Upload en cours...',
    epSave: 'Enregistrer les modifications',
    epDateBirth: 'Date de Naissance',
    epDatePlaceholder: 'JJ/MM/AAAA',
    epGender: 'Genre',
    epMale: 'Homme',
    epFemale: 'Femme',
    epOther: 'Autre',
    epBloodGroup: 'Groupe Sanguin',
    epBloodSelect: 'Sélectionner',
    epHeight: 'Taille (m)',
    epWeight: 'Poids (kg)',
    epPhotoOptions: 'Photo de profil',
    epTakePhoto: 'Prendre une photo',
    epGallery: 'Choisir depuis la galerie',
    epDeletePhoto: 'Supprimer la photo',
    epConfirmDate: 'Confirmer',
    epBirthTitle: 'Date de naissance',
    epBloodTitle: 'Groupe sanguin',
    epErrLoad: 'Impossible de charger le profil.',
    epErrSave: 'Erreur lors de la sauvegarde.',
    epErrPhoto: 'Impossible d\'uploader la photo.',
    epPhotoUpdated: 'Photo mise à jour avec succès',
    epDeleteConfirmTitle: 'Supprimer la photo',
    epDeleteConfirmMsg: 'Voulez-vous vraiment supprimer votre photo de profil ?',
    epErrPermissions: 'Autorisez l\'accès à la caméra et à la galerie.',
    epPermTitle: 'Permissions requises',
    emTitle: 'Urgences',
    emMedTitle: 'Urgence Médicale',
    emDesc: 'En cas d\'urgence médicale, appuyez sur le bouton ci-dessous pour contacter immédiatement les services d\'urgence.',
    emCallBtn: 'Appeler les Urgences',
    em24h: 'Ce service est disponible 24h/24 et 7j/7',
    emWarning: 'N\'utilisez ce service qu\'en cas d\'urgence réelle',
    emCallTitle: 'Appel d\'urgence',
    emCallMsg: 'Voulez-vous appeler le',
    emCallAction: 'Appeler',
    emCallError: 'Impossible de passer l\'appel',
    faqTitle: 'Questions Fréquentes',
    faqSearchPlaceholder: 'Rechercher une question...',
    faqCatAll: 'Tous',
    faqCatAccount: 'Compte',
    faqCatAppointments: 'Rendez-vous',
    faqCatPayment: 'Paiement',
    faqCatTechnical: 'Technique',
    faqBannerTitle: 'Besoin d\'aide ?',
    faqBannerText: 'Parcourez nos questions fréquentes ou contactez notre support',
    faqEmpty: 'Aucune question trouvée',
    faqEmptySub: 'Essayez avec d\'autres mots-clés',
    faqSupportTitle: 'Vous n\'avez pas trouvé de réponse ?',
    faqSupportSub: 'Notre équipe est là pour vous aider',
    faqPhone: 'Téléphone',
    favTitle: 'Mes Favoris',
    favAll: 'Tous',
    favPharmacies: 'Pharmacies',
    favHospitals: 'Hôpitaux',
    favDirections: 'Itinéraire',
    favEmpty: 'Aucun favori',
    favEmptySub: 'Ajoutez des pharmacies ou hôpitaux à vos favoris',
    fpTitle: 'Mot de passe oublié ?',
    fpDesc1: 'Entrez votre email ou votre numéro de téléphone,',
    fpDesc2: 'nous vous enverrons un code de confirmation',
    fpTabPhone: 'Téléphone',
    fpEmailPlaceholder: 'exemple@email.com',
    fpPhonePlaceholder: '0612345678',
    fpResetBtn: 'Réinitialiser le mot de passe',
    fpErrEmail: 'Veuillez entrer un email valide',
    fpErrPhone: 'Veuillez entrer un numéro de téléphone valide',
    hiTitle: 'Santé & Prévention',
    hiHeroTitle: 'Protection précoce pour votre famille',
    hiHeroDesc: 'Découvrez nos conseils et guides pour maintenir votre famille en bonne santé',
    hiTopicsTitle: 'Thèmes de santé',
    hiTipsTitle: 'Conseils rapides',
    hiEmergencyTitle: 'Urgence médicale ?',
    hiEmergencyDesc: 'Contactez immédiatement les services d\'urgence',
    hiEmergencyBtn: 'Appeler',
    hiVaccination: 'Vaccination',
    hiVaccinationDesc: 'Calendrier vaccinal et rappels importants',
    hiPrevention: 'Prévention',
    hiPreventionDesc: 'Conseils pour prévenir les maladies',
    hiNutrition: 'Nutrition',
    hiNutritionDesc: 'Guide alimentaire pour toute la famille',
    hiPediatrics: 'Pédiatrie',
    hiPediatricsDesc: 'Suivi de santé pour vos enfants',
    hiFitness: 'Activité Physique',
    hiFitnessDesc: 'Exercices et recommandations',
    hiHydration: 'Hydratation',
    hiHydrationDesc: 'Importance de boire suffisamment d\'eau',
    hiTip1Title: 'Lavez-vous les mains régulièrement',
    hiTip1: 'Pendant au moins 20 secondes avec du savon',
    hiTip2Title: 'Dormez suffisamment',
    hiTip2: '7-9 heures pour les adultes, plus pour les enfants',
    hiTip3Title: 'Mangez équilibré',
    hiTip3: '5 fruits et légumes par jour minimum',
    hiTip4Title: 'Restez actif',
    hiTip4: 'Au moins 30 minutes d\'activité physique par jour',
    hsTitle: 'Hôpitaux & Cliniques',
    hsLoading: 'Chargement depuis OpenStreetMap...',
    hsLoadingFirst: 'Première ouverture — peut prendre 5-10 secondes (données mises en cache ensuite)',
    hsConnectError: 'Connexion impossible',
    hsEmpty: 'Aucun établissement dans cette région',
    hsSearchPlaceholder: 'Nom, spécialité...',
    hsEmergencyOnly: 'Urgences 24h seulement',
    hsEmergencyBadge: 'Urgences 24h',
    hsLocDenied: 'Activer la localisation pour voir les distances',
    hsLocGranted: 'Triés par distance depuis votre position',
    hsAllEstablishments: 'Tous les établissements',
    hsRegion: 'Région',
    hsRegAll: 'Toutes',
    hsRegMaritime: 'Maritime',
    hsRegPlateaux: 'Plateaux',
    hsRegCentrale: 'Centrale',
    hsRegKara: 'Kara',
    hsRegSavanes: 'Savanes',
    hsNoPhone: 'Numéro non renseigné',
    hsOpen247: 'Ouvert 24h/24 — 7j/7',
    hsNoHours: 'Horaires non renseignés',
    hsDistanceFrom: 'À',
    hsDistanceFromPos: 'de votre position',
    hsSpecialties: 'Spécialités :',
    loginTitle: 'Connexion',
    loginWelcome: 'Bon retour !',
    loginSubtitle: 'Connectez-vous pour accéder à votre compte',
    loginEmailPlaceholder: 'Entrez votre email',
    loginPasswordPlaceholder: 'Entrez votre mot de passe',
    loginForgotPassword: 'Mot de passe oublié ?',
    loginBtn: 'Connexion',
    loginNoAccount: 'Vous n\'avez pas de compte ? ',
    loginSignup: 'Inscription',
    loginOr: 'OU',
    loginGoogle: 'Se connecter avec Google',
    loginApple: 'Se connecter avec Apple',
    loginFacebook: 'Se connecter avec Facebook',
    loginErrEmail: 'Email invalide',
    loginErrPassword: 'Mot de passe trop court',
    loginErrServer: 'Erreur de connexion au serveur',
    loginSuccessTitle: 'Bon retour !',
    loginSuccessDesc1: 'Vous vous êtes connecté avec succès',
    loginSuccessDesc2: 'à l\'application MyHospital',
    loginSuccessBtn: 'Aller à l\'accueil',
    loginLangTitle: '🌐 Choisir la langue',
    ndDetails: 'Détails',
    ndTypeAppointment: 'Rendez-vous',
    ndTypeStatus: 'Mise à jour',
    ndTypeGeneral: 'Information',
    ndMessage: 'Message',
    ndQuickActions: 'Actions rapides',
    ndViewAppointments: 'Voir mes rendez-vous',
    ndDirections: 'Itinéraire',
    ndCallDoctor: 'Appeler le médecin',
    ndViewDetails: 'Voir les détails',
    ndLearnMore: 'En savoir plus',
    ndMoreInfo: 'Plus d\'informations',
    ndDelete: 'Supprimer',
    notifTitle: 'Notifications',
    notifLoading: 'Chargement...',
    notifConnectError: 'Connexion impossible',
    notifLoadError: 'Impossible de charger les notifications.',
    notifEmpty: 'Aucune notification',
    notifEmptySub: 'Vous n\'avez pas encore reçu de notification.',
    notifUnread: 'notification non lue',
    notifUnreadPlural: 'notifications non lues',
    notifMarkAll: 'Tout lire',
    notifDeleteTitle: 'Supprimer la notification',
    notifDeleteMsg: 'Voulez-vous supprimer cette notification ?',
    notifRetry: 'Réessayer',
    signupMonth1: 'Janvier', signupMonth2: 'Février', signupMonth3: 'Mars', signupMonth4: 'Avril',
    signupMonth5: 'Mai', signupMonth6: 'Juin', signupMonth7: 'Juillet', signupMonth8: 'Août',
    signupMonth9: 'Septembre', signupMonth10: 'Octobre', signupMonth11: 'Novembre', signupMonth12: 'Décembre',
    signupTitle: 'Inscription',
    welcomeStart: 'Commençons !', welcomeDesc1: 'Connectez-vous pour profiter des fonctionnalités', welcomeDesc2: 'que nous avons fournies et restez en bonne santé !',
    welcomeLogin: 'Connexion', welcomeSignup: 'Inscription',
    settingsTitle: 'Paramètres', settingsAccount: 'COMPTE', settingsAccountInfo: 'Informations du compte',
    settingsAccountInfoSub: 'Modifier votre profil', settingsPrivacy: 'Confidentialité et sécurité',
    settingsPrivacySub: 'Gérer vos données', settingsChangePassword: 'Changer le mot de passe',
    settingsNotif: 'NOTIFICATIONS', settingsPush: 'Notifications Push',
    settingsPushSub: 'Recevoir des alertes sur votre téléphone', settingsEmailNotif: 'Notifications Email',
    settingsEmailSub: 'Recevoir des mises à jour par email', settingsSmsNotif: 'Notifications SMS',
    settingsSmsSub: 'Recevoir des rappels par SMS', settingsPrefs: 'PRÉFÉRENCES',
    settingsLang: 'Langue', settingsTheme: 'Thème', settingsDark: 'Mode sombre', settingsLight: 'Mode clair',
    settingsLocation: 'Services de localisation', settingsLocationSub: 'Trouver des hôpitaux à proximité',
    settingsPayment: 'PAIEMENT', settingsPaymentMethods: 'Moyens de paiement',
    settingsPaymentSub: 'Gérer vos moyens de paiement', settingsTransactionHistory: 'Historique des transactions',
    settingsHelp: 'AIDE ET SUPPORT', settingsHelpCenter: 'Centre d\'aide (FAQs)',
    settingsTerms: 'Conditions d\'utilisation', settingsAbout: 'À PROPOS', settingsAppVersion: 'Version de l\'application',
    settingsRateApp: 'Noter l\'application', settingsShareApp: 'Partager l\'application',
    settings: 'Paramètres', imc: 'IMC',
    logoutTitle: 'Êtes-vous sûr de vouloir vous', logoutTitle2: 'déconnecter ?',
    splashTagline: 'Votre santé, notre priorité',
    dlLocationTitle: 'Configurez votre lieu de consultation',
    dlLocationSubtitle: 'Pour que les patients puissent vous trouver facilement',
    dlUseMyLocation: 'Utiliser ma position actuelle',
    dlSearchOnMap: 'Rechercher sur la carte',
    dlAddressPlaceholder: 'Entrez une adresse, un hôpital, un quartier...',
    dlIndicationLabel: 'Indication complémentaire (optionnelle)',
    dlIndicationPlaceholder: 'Ex: Immeuble bleu, 2e étage, en face de la pharmacie...',
    dlSaveLocation: 'Enregistrer le lieu',
    dlSaved: 'Lieu de consultation enregistré !',
    dlGettingLocation: 'Recherche de votre position...',
    dlPermissionDenied: 'Vous avez refusé la permission GPS. Veuillez utiliser la recherche sur carte.',
    dlGpsError: 'Impossible d\'obtenir votre position. Utilisez la recherche sur carte.',
    doctorCabinet: 'Lieu de consultation',
    doctorIndication: 'Indication',
    doctorOpenRoute: 'Ouvrir l\'itinéraire',
    doctorNotConfigured: 'Lieu de consultation non configuré',
  },
  en: {
    home: 'Home', profile: 'Profile', appointments: 'Appointments', notifications: 'Notifications',
    favorites: 'Favorites', editProfile: 'Edit Profile', language: 'Language', theme: 'Appearance',
    prescriptions: 'My Prescriptions', paymentMethod: 'Payment Method', faqs: 'FAQs', logout: 'Logout',
    save: 'Save', cancel: 'Cancel', confirm: 'Confirm', success: 'Success', error: 'Error', loading: 'Loading...',
    profileUpdated: 'Your profile has been updated successfully!', languageChanged: 'Language changed to',
    themeChanged: 'Theme changed successfully', firstName: 'First Name', lastName: 'Last Name', email: 'Email',
    phone: 'Phone', address: 'Address', city: 'City', dateOfBirth: 'Date of Birth', gender: 'Gender',
    bloodGroup: 'Blood Group', height: 'Height (m)', weight: 'Weight (kg)', male: 'Male', female: 'Female',
    other: 'Other', areYouSureLogout: 'Are you sure you want to logout?', healthInfo: 'Health Information',
    bloodType: 'Blood Type', age: 'Age', bmi: 'BMI Status', rdvCount: 'Appointments',
    noNotification: 'No notifications', noNotificationSub: 'You haven\'t received any notification yet.',
    markAllRead: 'Mark all read', bestDoctors: 'Best Doctors', seeAll: 'See all',
    searchPlaceholder: 'Search doctor, medications...', doctor: 'Doctor', pharmacy: 'Pharmacy',
    hospital: 'Hospital', ambulance: 'Ambulance', bannerTitle1: 'Early protection for',
    bannerTitle2: 'your family health', learnMore: 'Learn more', loadingDoctors: 'Loading doctors...',
    retryButton: 'Retry', noDoctors: 'No doctors available', cannotLoadDoctors: 'Unable to load doctors',
    aptTitle: 'Appointments', aptLoading: 'Loading your appointments...', aptPending: 'Pending',
    aptConfirmed: 'Confirmed', aptPast: 'Past', aptRejected: 'Rejected', aptOnline: 'Online',
    aptHome: 'Home visit', aptHospital: 'Hospital', aptMoreDetails: 'More details', aptHideDetails: 'Hide details',
    aptCall: 'Call', aptWhatsApp: 'WhatsApp', aptDirections: 'Directions', aptJoinVideo: 'Join consultation',
    aptConfirmedMsg: 'Appointment confirmed', aptReschedule: 'Reschedule', aptDelete: 'Delete',
    aptEmpty: 'No appointments', aptCancelTitle: 'Cancel appointment',
    aptCancelMsg: 'Are you sure you want to cancel this appointment?', aptDeleteTitle: 'Delete appointment',
    aptDeleteMsg: 'Are you sure you want to delete this appointment?', aptCancelSuccess: 'Appointment cancelled successfully',
    aptJoinTitle: 'Join consultation', aptJoinMsg: 'You will be redirected to the video call', aptJoin: 'Join',
    aptErrLoad: 'Unable to load your appointments. Please try again.', bkTitle: 'New appointment',
    bkTypeTitle: 'Consultation type', bkTypeSubtitle: 'Choose the type of consultation that suits you',
    bkOnline: 'Online consultation', bkOnlineDesc: 'Video consultation', bkHome: 'Home visit',
    bkHomeDesc: 'The doctor comes to you', bkHospital: 'Hospital consultation', bkHospitalDesc: 'In-person appointment',
    bkDescLabel: 'Problem description', bkDescPlaceholder: 'Briefly describe your health problem...',
    bkNext: 'Next', bkValidationMsg: 'Please select a type and add a description',
    cpTitle: 'Change password', cpInfo: 'Your password must contain at least 8 characters',
    cpCurrent: 'Current password', cpCurrentPlaceholder: 'Enter your current password', cpNew: 'New password',
    cpNewPlaceholder: 'Enter your new password', cpConfirm: 'Confirm new password',
    cpConfirmPlaceholder: 'Confirm your new password', cpForgot: 'Forgot password?', cpWeak: 'Weak',
    cpMedium: 'Medium', cpStrong: 'Strong', cpMatch: 'Passwords match', cpNoMatch: 'Passwords do not match',
    cpSave: 'Update password', cpSuccess: 'Your password has been changed successfully',
    cpErrCurrent: 'Please enter your current password', cpErrNew: 'Please enter a new password',
    cpErrLen: 'Password must contain at least 8 characters', cpErrSame: 'New password must be different from old password',
    cnpTitle: 'Create new password', cnpDesc: 'Create your new password to log in', cnpNew: 'New password',
    cnpConfirm: 'Confirm password', cnpCreate: 'Create password', cnpSuccess: 'You have successfully reset your password.',
    cnpErrLen: 'Password must contain at least 6 characters', cnpErrMatch: 'Passwords do not match', cnpLogin: 'Login',
    ddTitle: 'Doctor details', ddLoading: 'Loading...', ddRetry: 'Retry', ddAbout: 'About',
    ddExperience: 'years of experience', ddPatients: 'patients', ddDiplomas: 'Diplomas', ddPrices: 'Prices',
    ddAvailableDates: 'Available dates', ddLoadingDates: 'Loading availability...',
    ddNoDates: 'No availability in the next 30 days', ddAvailableSlots: 'Available slots',
    ddNoSlots: 'No slots available for this date', ddOccupied: 'occupied', ddFeeDetails: 'Fee details',
    ddConsultation: 'Consultation', ddConfirmFee: 'Confirmation fee', ddTotal: 'Total',
    ddNbOnline: 'The confirmation fee of', ddNbOnline2: 'FCFA is non-refundable whether the appointment is accepted or rejected.',
    ddNbOnlineLabel: 'Note:', ddPayOnSite: 'Payment on site:', ddPayOnSiteMsg: 'Payment will be made directly at the consultation.',
    ddSelectDate: 'Please select a date', ddSelectSlot: 'Please select a time slot',
    ddContinuePayment: 'Continue to payment', ddConfirmRdv: 'Confirm appointment',
    ddSuccessMsg: 'Your appointment has been created successfully!', ddConsultOnline: 'Online consultation',
    ddConsultHome: 'Home visit', ddConsultHospital: 'Hospital consultation',     ddCannotLoad: 'Unable to load doctor details',
    ddCabinet: 'Doctor\'s office',
    ddYourPosition: 'Your position',
    ddUseMyLocation: 'Use my current location',
    ddGettingLocation: 'Getting location...',
    ddChangeLocation: 'Change location',
    ddIndicationLabel: 'Additional information',
    ddOptional: 'Optional',
    ddIndicationPlaceholder: 'Ex: Blue house behind the church, near the pharmacy...',
    ddNoLocationMsg: 'If GPS fails, add additional information to help the doctor find you.',
    aptOpenRoute: 'Open route',
    aptShareLocation: 'Share via WhatsApp',
    dlTitle: 'Choose a doctor', dlSearchPlaceholder: 'Search for a doctor...', dlLoading: 'Loading doctors...',
    dlNoDoctor: 'No doctors found', dlTryOther: 'Try a different search', dlNoneForType: 'No doctors available for',
    dlRetry: 'Retry', dlCannotLoad: 'Unable to load doctors', epTitle: 'Edit Profile', epChangePhoto: 'Change photo',
    epUploading: 'Uploading...', epSave: 'Save changes', epDateBirth: 'Date of Birth', epDatePlaceholder: 'DD/MM/YYYY',
    epGender: 'Gender', epMale: 'Male', epFemale: 'Female', epOther: 'Other', epBloodGroup: 'Blood Group',
    epBloodSelect: 'Select', epHeight: 'Height (m)', epWeight: 'Weight (kg)', epPhotoOptions: 'Profile photo',
    epTakePhoto: 'Take a photo', epGallery: 'Choose from gallery', epDeletePhoto: 'Delete photo',
    epConfirmDate: 'Confirm', epBirthTitle: 'Date of birth', epBloodTitle: 'Blood group',
    epErrLoad: 'Unable to load profile.', epErrSave: 'Error saving.', epErrPhoto: 'Unable to upload photo.',
    epPhotoUpdated: 'Photo updated successfully', epDeleteConfirmTitle: 'Delete photo',
    epDeleteConfirmMsg: 'Do you really want to delete your profile photo?',
    epErrPermissions: 'Please allow access to camera and gallery.', epPermTitle: 'Permissions required',
    emTitle: 'Emergency', emMedTitle: 'Medical Emergency',
    emDesc: 'In case of a medical emergency, press the button below to immediately contact emergency services.',
    emCallBtn: 'Call Emergency', em24h: 'This service is available 24/7',
    emWarning: 'Only use this service in a real emergency', emCallTitle: 'Emergency call',
    emCallMsg: 'Do you want to call', emCallAction: 'Call', emCallError: 'Unable to make the call',
    faqTitle: 'Frequently Asked Questions', faqSearchPlaceholder: 'Search a question...', faqCatAll: 'All',
    faqCatAccount: 'Account', faqCatAppointments: 'Appointments', faqCatPayment: 'Payment', faqCatTechnical: 'Technical',
    faqBannerTitle: 'Need help?', faqBannerText: 'Browse our FAQ or contact our support', faqEmpty: 'No question found',
    faqEmptySub: 'Try with other keywords', faqSupportTitle: 'Didn\'t find an answer?',
    faqSupportSub: 'Our team is here to help', faqPhone: 'Phone', favTitle: 'My Favorites', favAll: 'All',
    favPharmacies: 'Pharmacies', favHospitals: 'Hospitals', favDirections: 'Directions', favEmpty: 'No favorites',
    favEmptySub: 'Add pharmacies or hospitals to your favorites', fpTitle: 'Forgot password?',
    fpDesc1: 'Enter your email or phone number,', fpDesc2: 'we will send you a confirmation code', fpTabPhone: 'Phone',
    fpEmailPlaceholder: 'example@email.com', fpPhonePlaceholder: '0612345678', fpResetBtn: 'Reset password',
    fpErrEmail: 'Please enter a valid email', fpErrPhone: 'Please enter a valid phone number',
    hiTitle: 'Health & Prevention', hiHeroTitle: 'Early protection for your family',
    hiHeroDesc: 'Discover our tips and guides to keep your family healthy', hiTopicsTitle: 'Health topics',
    hiTipsTitle: 'Quick tips', hiEmergencyTitle: 'Medical emergency?',
    hiEmergencyDesc: 'Immediately contact emergency services', hiEmergencyBtn: 'Call',
    hiVaccination: 'Vaccination', hiVaccinationDesc: 'Vaccination schedule and important reminders',
    hiPrevention: 'Prevention', hiPreventionDesc: 'Tips to prevent diseases', hiNutrition: 'Nutrition',
    hiNutritionDesc: 'Food guide for the whole family', hiPediatrics: 'Pediatrics',
    hiPediatricsDesc: 'Health monitoring for your children', hiFitness: 'Physical Activity',
    hiFitnessDesc: 'Exercises and recommendations', hiHydration: 'Hydration',
    hiHydrationDesc: 'Importance of drinking enough water', hiTip1Title: 'Wash your hands regularly',
    hiTip1: 'For at least 20 seconds with soap', hiTip2Title: 'Sleep enough',
    hiTip2: '7-9 hours for adults, more for children', hiTip3Title: 'Eat balanced',
    hiTip3: 'At least 5 fruits and vegetables per day', hiTip4Title: 'Stay active',
    hiTip4: 'At least 30 minutes of physical activity per day', hsTitle: 'Hospitals & Clinics',
    hsLoading: 'Loading from OpenStreetMap...', hsLoadingFirst: 'First load — may take 5-10 seconds (data cached afterwards)',
    hsConnectError: 'Connection failed', hsEmpty: 'No establishments in this region', hsSearchPlaceholder: 'Name, specialty...',
    hsEmergencyOnly: '24h emergency only', hsEmergencyBadge: '24h Emergency', hsLocDenied: 'Enable location to see distances',
    hsLocGranted: 'Sorted by distance from your position', hsAllEstablishments: 'All establishments', hsRegion: 'Region',
    hsRegAll: 'All', hsRegMaritime: 'Maritime', hsRegPlateaux: 'Plateaux', hsRegCentrale: 'Central', hsRegKara: 'Kara',
    hsRegSavanes: 'Savanes', hsNoPhone: 'No phone number', hsOpen247: 'Open 24/7', hsNoHours: 'Opening hours not available',
    hsDistanceFrom: '', hsDistanceFromPos: 'from your position', hsSpecialties: 'Specialties:',
    loginTitle: 'Login', loginWelcome: 'Welcome back!', loginSubtitle: 'Sign in to access your account',
    loginEmailPlaceholder: 'Enter your email', loginPasswordPlaceholder: 'Enter your password',
    loginForgotPassword: 'Forgot password?', loginBtn: 'Sign in', loginNoAccount: 'Don\'t have an account? ',
    loginSignup: 'Sign up', loginOr: 'OR', loginGoogle: 'Sign in with Google', loginApple: 'Sign in with Apple',
    loginFacebook: 'Sign in with Facebook', loginErrEmail: 'Invalid email', loginErrPassword: 'Password too short',
    loginErrServer: 'Server connection error', loginSuccessTitle: 'Welcome back!',
    loginSuccessDesc1: 'You have successfully signed in', loginSuccessDesc2: 'to the MyHospital app',
    loginSuccessBtn: 'Go to home', loginLangTitle: '🌐 Choose language',
    ndDetails: 'Details', ndTypeAppointment: 'Appointment', ndTypeStatus: 'Update', ndTypeGeneral: 'Information',
    ndMessage: 'Message', ndQuickActions: 'Quick actions', ndViewAppointments: 'View my appointments',
    ndDirections: 'Directions', ndCallDoctor: 'Call the doctor', ndViewDetails: 'View details',
    ndLearnMore: 'Learn more', ndMoreInfo: 'More information', ndDelete: 'Delete',
    notifTitle: 'Notifications', notifLoading: 'Loading...', notifConnectError: 'Connection failed',
    notifLoadError: 'Unable to load notifications.', notifEmpty: 'No notifications',
    notifEmptySub: 'You haven\'t received any notification yet.', notifUnread: 'unread notification',
    notifUnreadPlural: 'unread notifications', notifMarkAll: 'Mark all read', notifDeleteTitle: 'Delete notification',
    notifDeleteMsg: 'Do you want to delete this notification?', notifRetry: 'Retry',
    signupMonth1: 'January', signupMonth2: 'February', signupMonth3: 'March', signupMonth4: 'April',
    signupMonth5: 'May', signupMonth6: 'June', signupMonth7: 'July', signupMonth8: 'August',
    signupMonth9: 'September', signupMonth10: 'October', signupMonth11: 'November', signupMonth12: 'December',
    signupTitle: 'Sign Up',
    welcomeStart: 'Let\'s start!', welcomeDesc1: 'Log in to enjoy the features', welcomeDesc2: 'we provide and stay healthy!',
    welcomeLogin: 'Login', welcomeSignup: 'Sign Up',
    settingsTitle: 'Settings', settingsAccount: 'ACCOUNT', settingsAccountInfo: 'Account information',
    settingsAccountInfoSub: 'Edit your profile', settingsPrivacy: 'Privacy and security',
    settingsPrivacySub: 'Manage your data', settingsChangePassword: 'Change password',
    settingsNotif: 'NOTIFICATIONS', settingsPush: 'Push notifications',
    settingsPushSub: 'Receive alerts on your phone', settingsEmailNotif: 'Email notifications',
    settingsEmailSub: 'Receive updates by email', settingsSmsNotif: 'SMS notifications',
    settingsSmsSub: 'Receive reminders by SMS', settingsPrefs: 'PREFERENCES',
    settingsLang: 'Language', settingsTheme: 'Theme', settingsDark: 'Dark mode', settingsLight: 'Light mode',
    settingsLocation: 'Location services', settingsLocationSub: 'Find nearby hospitals',
    settingsPayment: 'PAYMENT', settingsPaymentMethods: 'Payment methods',
    settingsPaymentSub: 'Manage your payment methods', settingsTransactionHistory: 'Transaction history',
    settingsHelp: 'HELP AND SUPPORT', settingsHelpCenter: 'Help center (FAQs)',
    settingsTerms: 'Terms of use', settingsAbout: 'ABOUT', settingsAppVersion: 'App version',
    settingsRateApp: 'Rate the app', settingsShareApp: 'Share the app',
    settings: 'Settings', imc: 'BMI',
    logoutTitle: 'Are you sure you want to', logoutTitle2: 'log out?',
    splashTagline: 'Your health, our priority',
    dlLocationTitle: 'Set your consultation location',
    dlLocationSubtitle: 'So patients can find you easily',
    dlUseMyLocation: 'Use my current location',
    dlSearchOnMap: 'Search on map',
    dlAddressPlaceholder: 'Enter an address, hospital, neighborhood...',
    dlIndicationLabel: 'Additional information (optional)',
    dlIndicationPlaceholder: 'Ex: Blue building, 2nd floor, across from the pharmacy...',
    dlSaveLocation: 'Save location',
    dlSaved: 'Consultation location saved!',
    dlGettingLocation: 'Getting your location...',
    dlPermissionDenied: 'GPS permission denied. Please use the map search.',
    dlGpsError: 'Cannot get your position. Use the map search instead.',
    doctorCabinet: 'Consultation location',
    doctorIndication: 'Information',
    doctorOpenRoute: 'Open route',
    doctorNotConfigured: 'Location not configured',
  },
  de: {
    home: 'Startseite', profile: 'Profil', appointments: 'Termine', notifications: 'Benachrichtigungen',
    favorites: 'Favoriten', editProfile: 'Profil bearbeiten', language: 'Sprache', theme: 'Erscheinungsbild',
    prescriptions: 'Meine Rezepte', paymentMethod: 'Zahlungsmethode', faqs: 'FAQs', logout: 'Abmelden',
    save: 'Speichern', cancel: 'Abbrechen', confirm: 'Bestätigen', success: 'Erfolg', error: 'Fehler', loading: 'Laden...',
    profileUpdated: 'Ihr Profil wurde erfolgreich aktualisiert!', languageChanged: 'Sprache geändert zu',
    themeChanged: 'Thema erfolgreich geändert', firstName: 'Vorname', lastName: 'Nachname', email: 'E-Mail',
    phone: 'Telefon', address: 'Adresse', city: 'Stadt', dateOfBirth: 'Geburtsdatum', gender: 'Geschlecht',
    bloodGroup: 'Blutgruppe', height: 'Größe (m)', weight: 'Gewicht (kg)', male: 'Männlich', female: 'Weiblich',
    other: 'Sonstige', areYouSureLogout: 'Sind Sie sicher, dass Sie sich abmelden möchten?', healthInfo: 'Gesundheitsinformationen',
    bloodType: 'Blutgruppe', age: 'Alter', bmi: 'BMI-Status', rdvCount: 'Termine',
    noNotification: 'Keine Benachrichtigungen', noNotificationSub: 'Sie haben noch keine Benachrichtigung erhalten.',
    markAllRead: 'Alle als gelesen markieren', bestDoctors: 'Beste Ärzte', seeAll: 'Alle anzeigen',
    searchPlaceholder: 'Arzt, Medikamente suchen...', doctor: 'Arzt', pharmacy: 'Apotheke',
    hospital: 'Krankenhaus', ambulance: 'Krankenwagen', bannerTitle1: 'Früher Schutz für',
    bannerTitle2: 'die Gesundheit Ihrer Familie', learnMore: 'Mehr erfahren', loadingDoctors: 'Ärzte laden...',
    retryButton: 'Wiederholen', noDoctors: 'Keine Ärzte verfügbar', cannotLoadDoctors: 'Ärzte können nicht geladen werden',
    aptTitle: 'Termine', aptLoading: 'Ihre Termine werden geladen...', aptPending: 'Ausstehend',
    aptConfirmed: 'Bestätigt', aptPast: 'Vergangen', aptRejected: 'Abgelehnt', aptOnline: 'Online',
    aptHome: 'Hausbesuch', aptHospital: 'Krankenhaus', aptMoreDetails: 'Mehr Details', aptHideDetails: 'Details ausblenden',
    aptCall: 'Anrufen', aptWhatsApp: 'WhatsApp', aptDirections: 'Route', aptJoinVideo: 'Beratung beitreten',
    aptConfirmedMsg: 'Termin bestätigt', aptReschedule: 'Umbuchen', aptDelete: 'Löschen',
    aptEmpty: 'Keine Termine', aptCancelTitle: 'Termin stornieren',
    aptCancelMsg: 'Sind Sie sicher, dass Sie diesen Termin stornieren möchten?', aptDeleteTitle: 'Termin löschen',
    aptDeleteMsg: 'Sind Sie sicher, dass Sie diesen Termin löschen möchten?', aptCancelSuccess: 'Termin erfolgreich storniert',
    aptJoinTitle: 'Beratung beitreten', aptJoinMsg: 'Sie werden zum Videoanruf weitergeleitet', aptJoin: 'Beitreten',
    aptErrLoad: 'Ihre Termine können nicht geladen werden. Bitte versuchen Sie es erneut.', bkTitle: 'Neuer Termin',
    bkTypeTitle: 'Beratungsart', bkTypeSubtitle: 'Wählen Sie die Beratungsart, die zu Ihnen passt',
    bkOnline: 'Online-Beratung', bkOnlineDesc: 'Videoberatung', bkHome: 'Hausbesuch',
    bkHomeDesc: 'Der Arzt kommt zu Ihnen', bkHospital: 'Krankenhaus-Beratung', bkHospitalDesc: 'Termin vor Ort',
    bkDescLabel: 'Problembeschreibung', bkDescPlaceholder: 'Beschreiben Sie kurz Ihr Gesundheitsproblem...',
    bkNext: 'Weiter', bkValidationMsg: 'Bitte wählen Sie eine Art und fügen Sie eine Beschreibung hinzu',
    cpTitle: 'Passwort ändern', cpInfo: 'Ihr Passwort muss mindestens 8 Zeichen enthalten',
    cpCurrent: 'Aktuelles Passwort', cpCurrentPlaceholder: 'Geben Sie Ihr aktuelles Passwort ein', cpNew: 'Neues Passwort',
    cpNewPlaceholder: 'Geben Sie Ihr neues Passwort ein', cpConfirm: 'Neues Passwort bestätigen',
    cpConfirmPlaceholder: 'Bestätigen Sie Ihr neues Passwort', cpForgot: 'Passwort vergessen?', cpWeak: 'Schwach',
    cpMedium: 'Mittel', cpStrong: 'Stark', cpMatch: 'Passwörter stimmen überein', cpNoMatch: 'Passwörter stimmen nicht überein',
    cpSave: 'Passwort aktualisieren', cpSuccess: 'Ihr Passwort wurde erfolgreich geändert',
    cpErrCurrent: 'Bitte geben Sie Ihr aktuelles Passwort ein', cpErrNew: 'Bitte geben Sie ein neues Passwort ein',
    cpErrLen: 'Passwort muss mindestens 8 Zeichen enthalten', cpErrSame: 'Neues Passwort muss vom alten verschieden sein',
    cnpTitle: 'Neues Passwort erstellen', cnpDesc: 'Erstellen Sie Ihr neues Passwort zum Anmelden', cnpNew: 'Neues Passwort',
    cnpConfirm: 'Passwort bestätigen', cnpCreate: 'Passwort erstellen', cnpSuccess: 'Sie haben Ihr Passwort erfolgreich zurückgesetzt.',
    cnpErrLen: 'Passwort muss mindestens 6 Zeichen enthalten', cnpErrMatch: 'Passwörter stimmen nicht überein', cnpLogin: 'Anmelden',
    ddTitle: 'Arztdetails', ddLoading: 'Laden...', ddRetry: 'Wiederholen', ddAbout: 'Über',
    ddExperience: 'Jahre Erfahrung', ddPatients: 'Patienten', ddDiplomas: 'Diplome', ddPrices: 'Preise',
    ddAvailableDates: 'Verfügbare Daten', ddLoadingDates: 'Verfügbarkeit wird geladen...',
    ddNoDates: 'Keine Verfügbarkeit in den nächsten 30 Tagen', ddAvailableSlots: 'Verfügbare Zeitfenster',
    ddNoSlots: 'Keine Zeitfenster für dieses Datum verfügbar', ddOccupied: 'besetzt', ddFeeDetails: 'Gebührendetails',
    ddConsultation: 'Beratung', ddConfirmFee: 'Bestätigungsgebühr', ddTotal: 'Gesamt',
    ddNbOnline: 'Die Bestätigungsgebühr von', ddNbOnline2: 'FCFA ist nicht erstattbar, ob der Termin angenommen oder abgelehnt wird.',
    ddNbOnlineLabel: 'Hinweis:', ddPayOnSite: 'Zahlung vor Ort:', ddPayOnSiteMsg: 'Die Zahlung erfolgt direkt bei der Beratung.',
    ddSelectDate: 'Bitte wählen Sie ein Datum', ddSelectSlot: 'Bitte wählen Sie ein Zeitfenster',
    ddContinuePayment: 'Zur Zahlung fortfahren', ddConfirmRdv: 'Termin bestätigen',
    ddSuccessMsg: 'Ihr Termin wurde erfolgreich erstellt!', ddConsultOnline: 'Online-Beratung',
    ddConsultHome: 'Hausbesuch', ddConsultHospital: 'Krankenhaus-Beratung',     ddCannotLoad: 'Arztdetails können nicht geladen werden',
    ddCabinet: 'Arztpraxis',
    ddYourPosition: 'Ihre Position',
    ddUseMyLocation: 'Mein aktuelles Standort verwenden',
    ddGettingLocation: 'Standort wird ermittelt...',
    ddChangeLocation: 'Standort ändern',
    ddIndicationLabel: 'Zusätzliche Angabe',
    ddOptional: 'Optional',
    ddIndicationPlaceholder: 'Z.B. Blaues Haus hinter der Kirche, nahe der Apotheke...',
    ddNoLocationMsg: 'Falls GPS nicht funktioniert, fügen Sie eine zusätzliche Angabe hinzu, damit der Arzt Sie findet.',
    aptOpenRoute: 'Route öffnen',
    aptShareLocation: 'Per WhatsApp teilen',
    dlTitle: 'Arzt wählen', dlSearchPlaceholder: 'Arzt suchen...', dlLoading: 'Ärzte laden...',
    dlNoDoctor: 'Keine Ärzte gefunden', dlTryOther: 'Versuchen Sie eine andere Suche', dlNoneForType: 'Keine Ärzte verfügbar für',
    dlRetry: 'Wiederholen', dlCannotLoad: 'Ärzte können nicht geladen werden', epTitle: 'Profil bearbeiten', epChangePhoto: 'Foto ändern',
    epUploading: 'Hochladen...', epSave: 'Änderungen speichern', epDateBirth: 'Geburtsdatum', epDatePlaceholder: 'TT/MM/JJJJ',
    epGender: 'Geschlecht', epMale: 'Männlich', epFemale: 'Weiblich', epOther: 'Sonstige', epBloodGroup: 'Blutgruppe',
    epBloodSelect: 'Auswählen', epHeight: 'Größe (m)', epWeight: 'Gewicht (kg)', epPhotoOptions: 'Profilfoto',
    epTakePhoto: 'Foto aufnehmen', epGallery: 'Aus Galerie wählen', epDeletePhoto: 'Foto löschen',
    epConfirmDate: 'Bestätigen', epBirthTitle: 'Geburtsdatum', epBloodTitle: 'Blutgruppe',
    epErrLoad: 'Profil kann nicht geladen werden.', epErrSave: 'Fehler beim Speichern.', epErrPhoto: 'Foto kann nicht hochgeladen werden.',
    epPhotoUpdated: 'Foto erfolgreich aktualisiert', epDeleteConfirmTitle: 'Foto löschen',
    epDeleteConfirmMsg: 'Möchten Sie Ihr Profilfoto wirklich löschen?',
    epErrPermissions: 'Bitte erlauben Sie Zugriff auf Kamera und Galerie.', epPermTitle: 'Erforderliche Berechtigungen',
    emTitle: 'Notfall', emMedTitle: 'Medizinischer Notfall',
    emDesc: 'Im medizinischen Notfall drücken Sie die Taste unten, um sofort den Rettungsdienst zu kontaktieren.',
    emCallBtn: 'Notruf rufen', em24h: 'Dieser Service ist 24/7 verfügbar',
    emWarning: 'Nutzen Sie diesen Service nur im echten Notfall', emCallTitle: 'Notruf',
    emCallMsg: 'Möchten Sie anrufen', emCallAction: 'Anrufen', emCallError: 'Anruf kann nicht durchgeführt werden',
    faqTitle: 'Häufig gestellte Fragen', faqSearchPlaceholder: 'Frage suchen...', faqCatAll: 'Alle',
    faqCatAccount: 'Konto', faqCatAppointments: 'Termine', faqCatPayment: 'Zahlung', faqCatTechnical: 'Technisch',
    faqBannerTitle: 'Brauchen Sie Hilfe?', faqBannerText: 'Durchsuchen Sie unsere FAQ oder kontaktieren Sie unseren Support', faqEmpty: 'Keine Frage gefunden',
    faqEmptySub: 'Versuchen Sie andere Schlüsselwörter', faqSupportTitle: 'Keine Antwort gefunden?',
    faqSupportSub: 'Unser Team ist für Sie da', faqPhone: 'Telefon', favTitle: 'Meine Favoriten', favAll: 'Alle',
    favPharmacies: 'Apotheken', favHospitals: 'Krankenhäuser', favDirections: 'Route', favEmpty: 'Keine Favoriten',
    favEmptySub: 'Fügen Sie Apotheken oder Krankenhäuser zu Ihren Favoriten hinzu', fpTitle: 'Passwort vergessen?',
    fpDesc1: 'Geben Sie Ihre E-Mail oder Telefonnummer ein,', fpDesc2: 'wir senden Ihnen einen Bestätigungscode', fpTabPhone: 'Telefon',
    fpEmailPlaceholder: 'beispiel@email.com', fpPhonePlaceholder: '0612345678', fpResetBtn: 'Passwort zurücksetzen',
    fpErrEmail: 'Bitte geben Sie eine gültige E-Mail ein', fpErrPhone: 'Bitte geben Sie eine gültige Telefonnummer ein',
    hiTitle: 'Gesundheit & Prävention', hiHeroTitle: 'Früher Schutz für Ihre Familie',
    hiHeroDesc: 'Entdecken Sie unsere Tipps und Leitfäden für eine gesunde Familie', hiTopicsTitle: 'Gesundheitsthemen',
    hiTipsTitle: 'Schnelle Tipps', hiEmergencyTitle: 'Medizinischer Notfall?',
    hiEmergencyDesc: 'Kontaktieren Sie sofort den Rettungsdienst', hiEmergencyBtn: 'Anrufen',
    hiVaccination: 'Impfung', hiVaccinationDesc: 'Impfplan und wichtige Erinnerungen',
    hiPrevention: 'Prävention', hiPreventionDesc: 'Tipps zur Krankheitsvorbeugung', hiNutrition: 'Ernährung',
    hiNutritionDesc: 'Ernährungsleitfaden für die ganze Familie', hiPediatrics: 'Pädiatrie',
    hiPediatricsDesc: 'Gesundheitsüberwachung für Ihre Kinder', hiFitness: 'Physikalische Aktivität',
    hiFitnessDesc: 'Übungen und Empfehlungen', hiHydration: 'Hydratation',
    hiHydrationDesc: 'Wichtigkeit von ausreichendem Wassertrinken', hiTip1Title: 'Waschen Sie regelmäßig Ihre Hände',
    hiTip1: 'Mindestens 20 Sekunden mit Seife', hiTip2Title: 'Schlafen Sie genug',
    hiTip2: '7-9 Stunden für Erwachsene, mehr für Kinder', hiTip3Title: 'Essen Sie ausgewogen',
    hiTip3: 'Mindestens 5 Obst und Gemüse pro Tag', hiTip4Title: 'Bleiben Sie aktiv',
    hiTip4: 'Mindestens 30 Minuten physikalische Aktivität pro Tag', hsTitle: 'Krankenhäuser & Kliniken',
    hsLoading: 'Von OpenStreetMap laden...', hsLoadingFirst: 'Erstes Laden — kann 5-10 Sekunden dauern (danach zwischengespeichert)',
    hsConnectError: 'Verbindung fehlgeschlagen', hsEmpty: 'Keine Einrichtungen in dieser Region', hsSearchPlaceholder: 'Name, Fachrichtung...',
    hsEmergencyOnly: 'Nur 24h-Notfall', hsEmergencyBadge: '24h-Notfall', hsLocDenied: 'Standort aktivieren, um Entfernungen zu sehen',
    hsLocGranted: 'Nach Entfernung von Ihrem Standort sortiert', hsAllEstablishments: 'Alle Einrichtungen', hsRegion: 'Region',
    hsRegAll: 'Alle', hsRegMaritime: 'Maritime', hsRegPlateaux: 'Plateaux', hsRegCentrale: 'Centrale', hsRegKara: 'Kara',
    hsRegSavanes: 'Savanes', hsNoPhone: 'Keine Telefonnummer', hsOpen247: '24/7 geöffnet', hsNoHours: 'Öffnungszeiten nicht verfügbar',
    hsDistanceFrom: '', hsDistanceFromPos: 'von Ihrem Standort', hsSpecialties: 'Fachrichtungen:',
    loginTitle: 'Anmeldung', loginWelcome: 'Willkommen zurück!', loginSubtitle: 'Melden Sie sich an, um auf Ihr Konto zuzugreifen',
    loginEmailPlaceholder: 'Geben Sie Ihre E-Mail ein', loginPasswordPlaceholder: 'Geben Sie Ihr Passwort ein',
    loginForgotPassword: 'Passwort vergessen?', loginBtn: 'Anmelden', loginNoAccount: 'Noch kein Konto? ',
    loginSignup: 'Registrieren', loginOr: 'ODER', loginGoogle: 'Mit Google anmelden', loginApple: 'Mit Apple anmelden',
    loginFacebook: 'Mit Facebook anmelden', loginErrEmail: 'Ungültige E-Mail', loginErrPassword: 'Passwort zu kurz',
    loginErrServer: 'Server-Verbindungsfehler', loginSuccessTitle: 'Willkommen zurück!',
    loginSuccessDesc1: 'Sie haben sich erfolgreich angemeldet', loginSuccessDesc2: 'bei der MyHospital-App',
    loginSuccessBtn: 'Zur Startseite', loginLangTitle: '🌐 Sprache wählen',
    ndDetails: 'Details', ndTypeAppointment: 'Termin', ndTypeStatus: 'Update', ndTypeGeneral: 'Information',
    ndMessage: 'Nachricht', ndQuickActions: 'Schnellaktionen', ndViewAppointments: 'Meine Termine anzeigen',
    ndDirections: 'Route', ndCallDoctor: 'Arzt anrufen', ndViewDetails: 'Details anzeigen',
    ndLearnMore: 'Mehr erfahren', ndMoreInfo: 'Mehr Informationen', ndDelete: 'Löschen',
    notifTitle: 'Benachrichtigungen', notifLoading: 'Laden...', notifConnectError: 'Verbindung fehlgeschlagen',
    notifLoadError: 'Benachrichtigungen können nicht geladen werden.', notifEmpty: 'Keine Benachrichtigungen',
    notifEmptySub: 'Sie haben noch keine Benachrichtigung erhalten.', notifUnread: 'ungelesene Benachrichtigung',
    notifUnreadPlural: 'ungelesene Benachrichtigungen', notifMarkAll: 'Alle als gelesen markieren', notifDeleteTitle: 'Benachrichtigung löschen',
    notifDeleteMsg: 'Möchten Sie diese Benachrichtigung löschen?', notifRetry: 'Wiederholen',
    signupTitle: 'Registrieren', signupStep1: 'Konto erstellen', signupStep2: 'Zusätzliche Informationen',
    signupStep1Sub: 'Füllen Sie Ihre persönlichen Daten aus', signupStep2Sub: 'Vervollständigen Sie Ihr Profil',
    signupPasswordPlaceholder: 'Passwort (mind. 8 Zeichen)', signupConfirmPassword: 'Passwort bestätigen',
    signupNext: 'Weiter', signupSignUp: 'Registrieren', signupHaveAccount: 'Sie haben bereits ein Konto? ',
    signupSignIn: 'Anmelden', signupCountryPicker: 'Wählen Sie Ihr Land', signupCountrySearch: 'Land suchen...',
    signupPhonePlaceholder: 'Telefonnummer', signupDateOfBirth: 'Geburtsdatum',
    signupGender: 'Geschlecht', signupMale: 'Männlich', signupFemale: 'Weiblich', signupOther: 'Sonstige',
    signupBloodGroup: 'Blutgruppe', signupOptionalInfo: 'Zusätzliche Informationen (optional)',
    signupHeightPlaceholder: 'Größe (cm)', signupWeightPlaceholder: 'Gewicht (kg)',
    signupTermsAccept: 'Ich akzeptiere die ', signupTerms: 'Nutzungsbedingungen', signupAnd: ' und die ',
    signupPrivacy: 'Datenschutzrichtlinie', signupCountryTitle: 'Land auswählen',
    signupBirthTitle: 'Geburtsdatum', signupSuccessTitle: 'Registrierung erfolgreich!',
    signupSuccessDesc: 'Willkommen ', signupSuccessSub: 'Ihr Konto wurde erfolgreich erstellt',
    signupPasswordMatch: 'Passwörter stimmen überein', signupPasswordNoMatch: 'Passwörter stimmen nicht überein',
    signupTermsError: 'Bitte akzeptieren Sie die Bedingungen', signupErr: 'Fehler',
    welcomeStart: 'Los geht\'s!', welcomeDesc1: 'Melden Sie sich an, um die Funktionen', welcomeDesc2: 'zu nutzen und bleiben Sie gesund!',
    welcomeLogin: 'Anmelden', welcomeSignup: 'Registrieren',
    settingsTitle: 'Einstellungen', settingsAccount: 'KONTO', settingsAccountInfo: 'Kontoinformationen',
    settingsAccountInfoSub: 'Profil bearbeiten', settingsPrivacy: 'Datenschutz und Sicherheit',
    settingsPrivacySub: 'Ihre Daten verwalten', settingsChangePassword: 'Passwort ändern',
    settingsNotif: 'BENACHRICHTIGUNGEN', settingsPush: 'Push-Benachrichtigungen',
    settingsPushSub: 'Benachrichtigungen auf Ihrem Telefon erhalten', settingsEmailNotif: 'E-Mail-Benachrichtigungen',
    settingsEmailSub: 'Updates per E-Mail erhalten', settingsSmsNotif: 'SMS-Benachrichtigungen',
    settingsSmsSub: 'Erinnerungen per SMS erhalten', settingsPrefs: 'EINSTELLUNGEN',
    settingsLang: 'Sprache', settingsTheme: 'Thema', settingsDark: 'Dunkelmodus', settingsLight: 'Hellmodus',
    settingsLocation: 'Standortdienste', settingsLocationSub: 'Krankenhäuser in der Nähe finden',
    settingsPayment: 'ZAHLUNG', settingsPaymentMethods: 'Zahlungsmethoden',
    settingsPaymentSub: 'Zahlungsmethoden verwalten', settingsTransactionHistory: 'Transaktionsverlauf',
    settingsHelp: 'HILFE UND SUPPORT', settingsHelpCenter: 'Hilfecenter (FAQs)',
    settingsTerms: 'Nutzungsbedingungen', settingsAbout: 'ÜBER', settingsAppVersion: 'App-Version',
    settingsRateApp: 'App bewerten', settingsShareApp: 'App teilen',
    settings: 'Einstellungen', imc: 'BMI',
    logoutTitle: 'Sind Sie sicher, dass Sie sich', logoutTitle2: 'abmelden möchten?',
    splashTagline: 'Ihre Gesundheit, unsere Priorität',
    signupMonth1: 'Januar', signupMonth2: 'Februar', signupMonth3: 'März', signupMonth4: 'April',
    signupMonth5: 'Mai', signupMonth6: 'Juni', signupMonth7: 'Juli', signupMonth8: 'August',
    signupMonth9: 'September', signupMonth10: 'Oktober', signupMonth11: 'November', signupMonth12: 'Dezember',
    dlLocationTitle: 'Konfigurieren Sie Ihren Praxisstandort',
    dlLocationSubtitle: 'Damit Patienten Sie leicht finden können',
    dlUseMyLocation: 'Meinen aktuellen Standort verwenden',
    dlSearchOnMap: 'Auf Karte suchen',
    dlAddressPlaceholder: 'Adresse, Krankenhaus, Stadtteil eingeben...',
    dlIndicationLabel: 'Zusätzliche Angabe (optional)',
    dlIndicationPlaceholder: 'Z.B. Blaues Gebäude, 2. Stock, gegenüber der Apotheke...',
    dlSaveLocation: 'Standort speichern',
    dlSaved: 'Praxisstandort gespeichert!',
    dlGettingLocation: 'Ermittle Ihren Standort...',
    dlPermissionDenied: 'GPS-Berechtigung verweigert. Bitte nutzen Sie die Kartensuche.',
    dlGpsError: 'Standort konnte nicht ermittelt werden. Bitte nutzen Sie die Kartensuche.',
    doctorCabinet: 'Praxisstandort',
    doctorIndication: 'Angabe',
    doctorOpenRoute: 'Route öffnen',
    doctorNotConfigured: 'Standort nicht konfiguriert',
  },
};

// ─────────────────────────────────────────────────────────────
// ✅ SUPPRESSION des 3 lignes cassées :
//   export const i18n = new Localization(translations);  ← SUPPRIMÉ
//   i18n.enableFallback = true;                          ← SUPPRIMÉ
//   i18n.defaultLocale = 'fr';                           ← SUPPRIMÉ
//
// Ces lignes tentaient de construire Localization comme une classe,
// mais expo-localization est un MODULE (pas une classe constructible).
// La fonction t() ci-dessous gère les traductions sans i18n-js.
// ─────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────
// 🏷️ TYPES
// ─────────────────────────────────────────────────────────────
interface User {
  ville?: string | null;
  id: number;
  email: string;
  nom: string;
  prenom: string;
  roles?: string[];
  isDocteur?: boolean;
  docteurId?: number;
  hasConsultationLocation?: boolean;
}

interface Colors {
  background: string; text: string; subText: string;
  card: string; inputBackground: string; border: string;
}

interface AuthContextType {
  user: User | null;
  isAuthenticated: boolean;
  login: (user: User) => Promise<void>;
  logout: () => Promise<void>;
  updateUser: (user: User) => void;
}

interface AppContextType {
  colors: Colors;
  isDarkMode: boolean;
  toggleTheme: () => void;
  theme: 'light' | 'dark' | 'auto';
  setTheme: (theme: 'light' | 'dark' | 'auto') => Promise<void>;
  language: string;
  setLanguage: (code: string) => Promise<void>;
  t: (key: string) => string;
}

// ─────────────────────────────────────────────────────────────
// 🎨 COULEURS
// ─────────────────────────────────────────────────────────────
const lightColors: Colors = {
  background: '#ffffff', text: '#000000', subText: '#666666',
  card: '#f5f5f5', inputBackground: '#f0f0f0', border: '#e2e8f0',
};
const darkColors: Colors = {
  background: '#1a1a1a', text: '#ffffff', subText: '#b0b0b0',
  card: '#2a2a2a', inputBackground: '#333333', border: '#444444',
};

// ─────────────────────────────────────────────────────────────
// 📦 CONTEXTES
// ─────────────────────────────────────────────────────────────
const AuthContext = createContext<AuthContextType | undefined>(undefined);
const AppContext  = createContext<AppContextType  | undefined>(undefined);

// ─────────────────────────────────────────────────────────────
// 🏗️ PROVIDER UNIQUE
// ─────────────────────────────────────────────────────────────
export const AppProvider = ({ children }: { children: ReactNode }) => {

  const [user, setUser] = useState<User | null>(null);
  const [theme, setThemeState]       = useState<'light' | 'dark' | 'auto'>('light');
  const [isDarkMode, setIsDarkMode]  = useState(false);
  const [language, setLanguageState] = useState('fr');

  useEffect(() => {
    const load = async () => {
      try {
        const [savedUser, savedTheme, savedLanguage] = await Promise.all([
          AsyncStorage.getItem('user'),
          AsyncStorage.getItem('app_theme'),
          AsyncStorage.getItem('app_language'),
        ]);

        if (savedUser) setUser(JSON.parse(savedUser));

        if (savedLanguage) {
          setLanguageState(savedLanguage);
        } else {
          const deviceLocale = Localization.getLocales?.()?.[0]?.languageCode ?? 'fr';
          const supported    = ['fr', 'en', 'de'];
          setLanguageState(supported.includes(deviceLocale) ? deviceLocale : 'fr');
        }

        if (savedTheme) {
          setThemeState(savedTheme as 'light' | 'dark' | 'auto');
          setIsDarkMode(savedTheme === 'dark');
        }
      } catch (e) {
        console.error('Erreur chargement préférences:', e);
      }
    };
    load();
  }, []);

  const login = async (userData: User) => {
    await AsyncStorage.setItem('user', JSON.stringify(userData));
    setUser(userData);
  };

  const logout = async () => {
    await Promise.all([
      AsyncStorage.removeItem('user'),
      secureStorage.clearTokens(),
    ]);
    apiClient.setAuthToken(null);
    setUser(null);
  };

  const updateUser = (userData: User) => setUser(userData);

  const toggleTheme = () => {
    const newDark = !isDarkMode;
    setIsDarkMode(newDark);
    setThemeState(newDark ? 'dark' : 'light');
    AsyncStorage.setItem('app_theme', newDark ? 'dark' : 'light');
  };

  const setTheme = async (newTheme: 'light' | 'dark' | 'auto') => {
    setThemeState(newTheme);
    setIsDarkMode(newTheme === 'dark');
    await AsyncStorage.setItem('app_theme', newTheme);
  };

  const setLanguage = async (code: string) => {
    setLanguageState(code);
    await AsyncStorage.setItem('app_language', code);
  };

  const t = (key: string): string => {
    try {
      const dict = translations[language as keyof typeof translations] ?? translations['fr'];
      return (dict as any)[key] ?? (translations['fr'] as any)[key] ?? key;
    } catch {
      return key;
    }
  };

  const authValue: AuthContextType = {
    user, isAuthenticated: !!user, login, logout, updateUser,
  };

  const appValue: AppContextType = {
    colors: isDarkMode ? darkColors : lightColors,
    isDarkMode, toggleTheme,
    theme, setTheme,
    language, setLanguage,
    t,
  };

  return (
    <AuthContext.Provider value={authValue}>
      <AppContext.Provider value={appValue}>
        {children}
      </AppContext.Provider>
    </AuthContext.Provider>
  );
};

// ─────────────────────────────────────────────────────────────
// 🪝 HOOKS
// ─────────────────────────────────────────────────────────────
export const useAuth = () => {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error('useAuth must be used within an AppProvider');
  return ctx;
};

export const useApp = () => {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error('useApp must be used within an AppProvider');
  return ctx;
};