import AsyncStorage from "@react-native-async-storage/async-storage";
import { I18n } from "i18n-js";
import { createContext, ReactNode, useContext, useEffect, useState } from "react";
import * as Localization from "expo-localization";

const translations = {
  fr: {
    home: 'Accueil',
    profile: 'Profil',
    appointments: 'Rendez-vous',
    notifications: 'Notifications',
    favorites: 'Favoris',
    editProfile: 'Modifier le profil',
    language: 'Langue',
    theme: 'Apparence',
    prescriptions: 'Mes Ordonnances',
    paymentMethod: 'Moyen de Paiement',
    faqs: 'FAQs',
    logout: 'Déconnexion',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    success: 'Succès',
    error: 'Erreur',
    loading: 'Chargement...',
    profileUpdated: 'Votre profil a été mis à jour avec succès !',
    languageChanged: 'La langue a été changée en',
    themeChanged: 'Le thème a été modifié avec succès',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Email',
    phone: 'Téléphone',
    address: 'Adresse',
    city: 'Ville',
    dateOfBirth: 'Date de Naissance',
    gender: 'Genre',
    bloodGroup: 'Groupe Sanguin',
    height: 'Taille (m)',
    weight: 'Poids (kg)',
    male: 'Homme',
    female: 'Femme',
    other: 'Autre',
    areYouSureLogout: 'Êtes-vous sûr de vouloir vous déconnecter ?',
    healthInfo: 'Informations de santé',
    bloodType: 'Groupe sanguin',
    age: 'Âge',
    bmi: 'Statut IMC',
    rdvCount: 'Rendez-vous',
    noNotification: 'Aucune notification',
    noNotificationSub: 'Vous n\'avez pas encore reçu de notification.',
    markAllRead: 'Tout lire',
    bestDoctors: 'Meilleurs Docteurs',
    seeAll: 'Voir tout',
    searchPlaceholder: 'Rechercher médecin, médicaments...',
    doctor: 'Docteur',
    pharmacy: 'Pharmacie',
    hospital: 'Hôpital',
    ambulance: 'Ambulance',
    bannerTitle1: 'Protection précoce pour',
    bannerTitle2: 'la santé de votre famille',
    learnMore: 'En savoir plus',
    loadingDoctors: 'Chargement des médecins...',
    retryButton: 'Réessayer',
    noDoctors: 'Aucun médecin disponible',
    cannotLoadDoctors: 'Impossible de charger les médecins',
    aptTitle: 'Rendez-vous',
    aptLoading: 'Chargement de vos rendez-vous...',
    aptPending: 'En attente',
    aptConfirmed: 'Confirmé',
    aptPast: 'Passé',
    aptRejected: 'Refusé',
    aptOnline: 'En ligne',
    aptHome: 'À domicile',
    aptHospital: 'À l\'hôpital',
    aptMoreDetails: 'Plus de détails',
    aptHideDetails: 'Masquer les détails',
    aptCall: 'Appeler',
    aptWhatsApp: 'WhatsApp',
    aptDirections: 'Itinéraire',
    aptJoinVideo: 'Rejoindre la consultation',
    aptConfirmedMsg: 'Rendez-vous confirmé',
    aptReschedule: 'Reprogrammer',
    aptDelete: 'Supprimer',
    aptEmpty: 'Aucun rendez-vous',
    aptCancelTitle: 'Annuler le rendez-vous',
    aptCancelMsg: 'Êtes-vous sûr de vouloir annuler ce rendez-vous ?',
    aptDeleteTitle: 'Supprimer le rendez-vous',
    aptDeleteMsg: 'Êtes-vous sûr de vouloir supprimer ce rendez-vous ?',
    aptCancelSuccess: 'Rendez-vous annulé avec succès',
    aptJoinTitle: 'Rejoindre la consultation',
    aptJoinMsg: 'Vous allez être redirigé vers la vidéoconférence',
    aptJoin: 'Rejoindre',
    aptErrLoad: 'Impossible de charger vos rendez-vous. Veuillez réessayer.',
    bkTitle: 'Nouveau rendez-vous',
    bkTypeTitle: 'Type de consultation',
    bkTypeSubtitle: 'Choisissez le type de consultation qui vous convient',
    bkOnline: 'Consultation en ligne',
    bkOnlineDesc: 'Consultation par vidéo',
    bkHome: 'Consultation à domicile',
    bkHomeDesc: 'Le médecin vient chez vous',
    bkHospital: 'Consultation à l\'hôpital',
    bkHospitalDesc: 'Rendez-vous en présentiel',
    bkDescLabel: 'Description du problème',
    bkDescPlaceholder: 'Décrivez brièvement votre problème de santé...',
    bkNext: 'Suivant',
    bkValidationMsg: 'Veuillez sélectionner un type et ajouter une description',
    cpTitle: 'Changer le mot de passe',
    cpInfo: 'Votre mot de passe doit contenir au moins 8 caractères',
    cpCurrent: 'Mot de passe actuel',
    cpCurrentPlaceholder: 'Entrez votre mot de passe actuel',
    cpNew: 'Nouveau mot de passe',
    cpNewPlaceholder: 'Entrez votre nouveau mot de passe',
    cpConfirm: 'Confirmer le nouveau mot de passe',
    cpConfirmPlaceholder: 'Confirmez votre nouveau mot de passe',
    cpForgot: 'Mot de passe oublié ?',
    cpWeak: 'Faible',
    cpMedium: 'Moyen',
    cpStrong: 'Fort',
    cpMatch: 'Les mots de passe correspondent',
    cpNoMatch: 'Les mots de passe ne correspondent pas',
    cpSave: 'Mettre à jour le mot de passe',
    cpSuccess: 'Votre mot de passe a été modifié avec succès',
    cpErrCurrent: 'Veuillez entrer votre mot de passe actuel',
    cpErrNew: 'Veuillez entrer un nouveau mot de passe',
    cpErrLen: 'Le mot de passe doit contenir au moins 8 caractères',
    cpErrSame: 'Le nouveau mot de passe doit être différent de l\'ancien',
    cnpTitle: 'Créer un nouveau mot de passe',
    cnpDesc: 'Créez votre nouveau mot de passe pour vous connecter',
    cnpNew: 'Nouveau mot de passe',
    cnpConfirm: 'Confirmer le mot de passe',
    cnpCreate: 'Créer le mot de passe',
    cnpSuccess: 'Vous avez réinitialisé votre mot de passe avec succès.',
    cnpErrLen: 'Le mot de passe doit contenir au moins 6 caractères',
    cnpErrMatch: 'Les mots de passe ne correspondent pas',
    cnpLogin: 'Connexion',
    ddTitle: 'Détails du médecin',
    ddLoading: 'Chargement...',
    ddRetry: 'Réessayer',
    ddAbout: 'À propos',
    ddExperience: 'ans d\'expérience',
    ddPatients: 'patients',
    ddDiplomas: 'Diplômes',
    ddPrices: 'Tarifs',
    ddAvailableDates: 'Dates disponibles',
    ddLoadingDates: 'Chargement des disponibilités...',
    ddNoDates: 'Aucune disponibilité dans les 30 prochains jours',
    ddAvailableSlots: 'Créneaux disponibles',
    ddNoSlots: 'Aucun créneau disponible pour cette date',
    ddOccupied: 'occupé',
    ddFeeDetails: 'Détails des frais',
    ddConsultation: 'Consultation',
    ddConfirmFee: 'Frais de confirmation',
    ddTotal: 'Total',
    ddNbOnline: 'Les frais de confirmation de',
    ddNbOnline2: 'FCFA ne sont pas remboursables, que le rendez-vous soit accepté ou refusé.',
    ddNbOnlineLabel: 'NB :',
    ddPayOnSite: 'Paiement sur place :',
    ddPayOnSiteMsg: 'Le paiement se fera directement lors de la consultation.',
    ddSelectDate: 'Veuillez sélectionner une date',
    ddSelectSlot: 'Veuillez sélectionner un créneau horaire',
    ddContinuePayment: 'Continuer vers le paiement',
    ddConfirmRdv: 'Confirmer le rendez-vous',
    ddSuccessMsg: 'Votre rendez-vous a été créé avec succès !',
    ddConsultOnline: 'Consultation en ligne',
    ddConsultHome: 'Consultation à domicile',
    ddConsultHospital: 'Consultation à l\'hôpital',
    ddCannotLoad: 'Impossible de charger les détails du médecin',
    dlTitle: 'Choisir un médecin',
    dlSearchPlaceholder: 'Rechercher un médecin...',
    dlLoading: 'Chargement des médecins...',
    dlNoDoctor: 'Aucun médecin trouvé',
    dlTryOther: 'Essayez une autre recherche',
    dlNoneForType: 'Aucun médecin disponible pour',
    dlRetry: 'Réessayer',
    dlCannotLoad: 'Impossible de charger les médecins',
    epTitle: 'Modifier le Profil',
    epChangePhoto: 'Changer la photo',
    epUploading: 'Upload en cours...',
    epSave: 'Enregistrer les modifications',
    epDateBirth: 'Date de Naissance',
    epDatePlaceholder: 'JJ/MM/AAAA',
    epGender: 'Genre',
    epMale: 'Homme',
    epFemale: 'Femme',
    epOther: 'Autre',
    epBloodGroup: 'Groupe Sanguin',
    epBloodSelect: 'Sélectionner',
    epHeight: 'Taille (m)',
    epWeight: 'Poids (kg)',
    epPhotoOptions: 'Photo de profil',
    epTakePhoto: 'Prendre une photo',
    epGallery: 'Choisir depuis la galerie',
    epDeletePhoto: 'Supprimer la photo',
    epConfirmDate: 'Confirmer',
    epBirthTitle: 'Date de naissance',
    epBloodTitle: 'Groupe sanguin',
    epErrLoad: 'Impossible de charger le profil.',
    epErrSave: 'Erreur lors de la sauvegarde.',
    epErrPhoto: 'Impossible d\'uploader la photo.',
    epPhotoUpdated: 'Photo mise à jour avec succès',
    epDeleteConfirmTitle: 'Supprimer la photo',
    epDeleteConfirmMsg: 'Voulez-vous vraiment supprimer votre photo de profil ?',
    epErrPermissions: 'Autorisez l\'accès à la caméra et à la galerie.',
    epPermTitle: 'Permissions requises',
    emTitle: 'Urgences',
    emMedTitle: 'Urgence Médicale',
    emDesc: 'En cas d\'urgence médicale, appuyez sur le bouton ci-dessous pour contacter immédiatement les services d\'urgence.',
    emCallBtn: 'Appeler les Urgences',
    em24h: 'Ce service est disponible 24h/24 et 7j/7',
    emWarning: 'N\'utilisez ce service qu\'en cas d\'urgence réelle',
    emCallTitle: 'Appel d\'urgence',
    emCallMsg: 'Voulez-vous appeler le',
    emCallAction: 'Appeler',
    emCallError: 'Impossible de passer l\'appel',
    faqTitle: 'Questions Fréquentes',
    faqSearchPlaceholder: 'Rechercher une question...',
    faqCatAll: 'Tous',
    faqCatAccount: 'Compte',
    faqCatAppointments: 'Rendez-vous',
    faqCatPayment: 'Paiement',
    faqCatTechnical: 'Technique',
    faqBannerTitle: 'Besoin d\'aide ?',
    faqBannerText: 'Parcourez nos questions fréquentes ou contactez notre support',
    faqEmpty: 'Aucune question trouvée',
    faqEmptySub: 'Essayez avec d\'autres mots-clés',
    faqSupportTitle: 'Vous n\'avez pas trouvé de réponse ?',
    faqSupportSub: 'Notre équipe est là pour vous aider',
    faqPhone: 'Téléphone',
    favTitle: 'Mes Favoris',
    favAll: 'Tous',
    favPharmacies: 'Pharmacies',
    favHospitals: 'Hôpitaux',
    favDirections: 'Itinéraire',
    favEmpty: 'Aucun favori',
    favEmptySub: 'Ajoutez des pharmacies ou hôpitaux à vos favoris',
    fpTitle: 'Mot de passe oublié ?',
    fpDesc1: 'Entrez votre email ou votre numéro de téléphone,',
    fpDesc2: 'nous vous enverrons un code de confirmation',
    fpTabPhone: 'Téléphone',
    fpEmailPlaceholder: 'exemple@email.com',
    fpPhonePlaceholder: '0612345678',
    fpResetBtn: 'Réinitialiser le mot de passe',
    fpErrEmail: 'Veuillez entrer un email valide',
    fpErrPhone: 'Veuillez entrer un numéro de téléphone valide',
    hiTitle: 'Santé & Prévention',
    hiHeroTitle: 'Protection précoce pour votre famille',
    hiHeroDesc: 'Découvrez nos conseils et guides pour maintenir votre famille en bonne santé',
    hiTopicsTitle: 'Thèmes de santé',
    hiTipsTitle: 'Conseils rapides',
    hiEmergencyTitle: 'Urgence médicale ?',
    hiEmergencyDesc: 'Contactez immédiatement les services d\'urgence',
    hiEmergencyBtn: 'Appeler',
    hiVaccination: 'Vaccination',
    hiVaccinationDesc: 'Calendrier vaccinal et rappels importants',
    hiPrevention: 'Prévention',
    hiPreventionDesc: 'Conseils pour prévenir les maladies',
    hiNutrition: 'Nutrition',
    hiNutritionDesc: 'Guide alimentaire pour toute la famille',
    hiPediatrics: 'Pédiatrie',
    hiPediatricsDesc: 'Suivi de santé pour vos enfants',
    hiFitness: 'Activité Physique',
    hiFitnessDesc: 'Exercices et recommandations',
    hiHydration: 'Hydratation',
    hiHydrationDesc: 'Importance de boire suffisamment d\'eau',
    hiTip1Title: 'Lavez-vous les mains régulièrement',
    hiTip1: 'Pendant au moins 20 secondes avec du savon',
    hiTip2Title: 'Dormez suffisamment',
    hiTip2: '7-9 heures pour les adultes, plus pour les enfants',
    hiTip3Title: 'Mangez équilibré',
    hiTip3: '5 fruits et légumes par jour minimum',
    hiTip4Title: 'Restez actif',
    hiTip4: 'Au moins 30 minutes d\'activité physique par jour',
  },
  en: {
    home: 'Home',
    profile: 'Profile',
    appointments: 'Appointments',
    notifications: 'Notifications',
    favorites: 'Favorites',
    editProfile: 'Edit Profile',
    language: 'Language',
    theme: 'Appearance',
    prescriptions: 'My Prescriptions',
    paymentMethod: 'Payment Method',
    faqs: 'FAQs',
    logout: 'Logout',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    success: 'Success',
    error: 'Error',
    loading: 'Loading...',
    profileUpdated: 'Your profile has been updated successfully!',
    languageChanged: 'Language changed to',
    themeChanged: 'Theme changed successfully',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    city: 'City',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    bloodGroup: 'Blood Group',
    height: 'Height (m)',
    weight: 'Weight (kg)',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    areYouSureLogout: 'Are you sure you want to logout?',
    healthInfo: 'Health Information',
    bloodType: 'Blood Type',
    age: 'Age',
    bmi: 'BMI Status',
    rdvCount: 'Appointments',
    noNotification: 'No notifications',
    noNotificationSub: 'You haven\'t received any notification yet.',
    markAllRead: 'Mark all read',
    bestDoctors: 'Best Doctors',
    seeAll: 'See all',
    searchPlaceholder: 'Search doctor, medications...',
    doctor: 'Doctor',
    pharmacy: 'Pharmacy',
    hospital: 'Hospital',
    ambulance: 'Ambulance',
    bannerTitle1: 'Early protection for',
    bannerTitle2: 'your family health',
    learnMore: 'Learn more',
    loadingDoctors: 'Loading doctors...',
    retryButton: 'Retry',
    noDoctors: 'No doctors available',
    cannotLoadDoctors: 'Unable to load doctors',
    aptTitle: 'Appointments',
    aptLoading: 'Loading your appointments...',
    aptPending: 'Pending',
    aptConfirmed: 'Confirmed',
    aptPast: 'Past',
    aptRejected: 'Rejected',
    aptOnline: 'Online',
    aptHome: 'Home visit',
    aptHospital: 'Hospital',
    aptMoreDetails: 'More details',
    aptHideDetails: 'Hide details',
    aptCall: 'Call',
    aptWhatsApp: 'WhatsApp',
    aptDirections: 'Directions',
    aptJoinVideo: 'Join consultation',
    aptConfirmedMsg: 'Appointment confirmed',
    aptReschedule: 'Reschedule',
    aptDelete: 'Delete',
    aptEmpty: 'No appointments',
    aptCancelTitle: 'Cancel appointment',
    aptCancelMsg: 'Are you sure you want to cancel this appointment?',
    aptDeleteTitle: 'Delete appointment',
    aptDeleteMsg: 'Are you sure you want to delete this appointment?',
    aptCancelSuccess: 'Appointment cancelled successfully',
    aptJoinTitle: 'Join consultation',
    aptJoinMsg: 'You will be redirected to the video call',
    aptJoin: 'Join',
    aptErrLoad: 'Unable to load your appointments. Please try again.',
    bkTitle: 'New appointment',
    bkTypeTitle: 'Consultation type',
    bkTypeSubtitle: 'Choose the type of consultation that suits you',
    bkOnline: 'Online consultation',
    bkOnlineDesc: 'Video consultation',
    bkHome: 'Home visit',
    bkHomeDesc: 'The doctor comes to you',
    bkHospital: 'Hospital consultation',
    bkHospitalDesc: 'In-person appointment',
    bkDescLabel: 'Problem description',
    bkDescPlaceholder: 'Briefly describe your health problem...',
    bkNext: 'Next',
    bkValidationMsg: 'Please select a type and add a description',
    cpTitle: 'Change password',
    cpInfo: 'Your password must contain at least 8 characters',
    cpCurrent: 'Current password',
    cpCurrentPlaceholder: 'Enter your current password',
    cpNew: 'New password',
    cpNewPlaceholder: 'Enter your new password',
    cpConfirm: 'Confirm new password',
    cpConfirmPlaceholder: 'Confirm your new password',
    cpForgot: 'Forgot password?',
    cpWeak: 'Weak',
    cpMedium: 'Medium',
    cpStrong: 'Strong',
    cpMatch: 'Passwords match',
    cpNoMatch: 'Passwords do not match',
    cpSave: 'Update password',
    cpSuccess: 'Your password has been changed successfully',
    cpErrCurrent: 'Please enter your current password',
    cpErrNew: 'Please enter a new password',
    cpErrLen: 'Password must contain at least 8 characters',
    cpErrSame: 'New password must be different from old password',
    cnpTitle: 'Create new password',
    cnpDesc: 'Create your new password to log in',
    cnpNew: 'New password',
    cnpConfirm: 'Confirm password',
    cnpCreate: 'Create password',
    cnpSuccess: 'You have successfully reset your password.',
    cnpErrLen: 'Password must contain at least 6 characters',
    cnpErrMatch: 'Passwords do not match',
    cnpLogin: 'Login',
    ddTitle: 'Doctor details',
    ddLoading: 'Loading...',
    ddRetry: 'Retry',
    ddAbout: 'About',
    ddExperience: 'years of experience',
    ddPatients: 'patients',
    ddDiplomas: 'Diplomas',
    ddPrices: 'Prices',
    ddAvailableDates: 'Available dates',
    ddLoadingDates: 'Loading availability...',
    ddNoDates: 'No availability in the next 30 days',
    ddAvailableSlots: 'Available slots',
    ddNoSlots: 'No slots available for this date',
    ddOccupied: 'occupied',
    ddFeeDetails: 'Fee details',
    ddConsultation: 'Consultation',
    ddConfirmFee: 'Confirmation fee',
    ddTotal: 'Total',
    ddNbOnline: 'The confirmation fee of',
    ddNbOnline2: 'FCFA is non-refundable whether the appointment is accepted or rejected.',
    ddNbOnlineLabel: 'Note:',
    ddPayOnSite: 'Payment on site:',
    ddPayOnSiteMsg: 'Payment will be made directly at the consultation.',
    ddSelectDate: 'Please select a date',
    ddSelectSlot: 'Please select a time slot',
    ddContinuePayment: 'Continue to payment',
    ddConfirmRdv: 'Confirm appointment',
    ddSuccessMsg: 'Your appointment has been created successfully!',
    ddConsultOnline: 'Online consultation',
    ddConsultHome: 'Home visit',
    ddConsultHospital: 'Hospital consultation',
    ddCannotLoad: 'Unable to load doctor details',
    dlTitle: 'Choose a doctor',
    dlSearchPlaceholder: 'Search for a doctor...',
    dlLoading: 'Loading doctors...',
    dlNoDoctor: 'No doctors found',
    dlTryOther: 'Try a different search',
    dlNoneForType: 'No doctors available for',
    dlRetry: 'Retry',
    dlCannotLoad: 'Unable to load doctors',
    epTitle: 'Edit Profile',
    epChangePhoto: 'Change photo',
    epUploading: 'Uploading...',
    epSave: 'Save changes',
    epDateBirth: 'Date of Birth',
    epDatePlaceholder: 'DD/MM/YYYY',
    epGender: 'Gender',
    epMale: 'Male',
    epFemale: 'Female',
    epOther: 'Other',
    epBloodGroup: 'Blood Group',
    epBloodSelect: 'Select',
    epHeight: 'Height (m)',
    epWeight: 'Weight (kg)',
    epPhotoOptions: 'Profile photo',
    epTakePhoto: 'Take a photo',
    epGallery: 'Choose from gallery',
    epDeletePhoto: 'Delete photo',
    epConfirmDate: 'Confirm',
    epBirthTitle: 'Date of birth',
    epBloodTitle: 'Blood group',
    epErrLoad: 'Unable to load profile.',
    epErrSave: 'Error saving.',
    epErrPhoto: 'Unable to upload photo.',
    epPhotoUpdated: 'Photo updated successfully',
    epDeleteConfirmTitle: 'Delete photo',
    epDeleteConfirmMsg: 'Do you really want to delete your profile photo?',
    epErrPermissions: 'Please allow access to camera and gallery.',
    epPermTitle: 'Permissions required',
    emTitle: 'Emergency',
    emMedTitle: 'Medical Emergency',
    emDesc: 'In case of a medical emergency, press the button below to immediately contact emergency services.',
    emCallBtn: 'Call Emergency',
    em24h: 'This service is available 24/7',
    emWarning: 'Only use this service in a real emergency',
    emCallTitle: 'Emergency call',
    emCallMsg: 'Do you want to call',
    emCallAction: 'Call',
    emCallError: 'Unable to make the call',
    faqTitle: 'Frequently Asked Questions',
    faqSearchPlaceholder: 'Search a question...',
    faqCatAll: 'All',
    faqCatAccount: 'Account',
    faqCatAppointments: 'Appointments',
    faqCatPayment: 'Payment',
    faqCatTechnical: 'Technical',
    faqBannerTitle: 'Need help?',
    faqBannerText: 'Browse our FAQ or contact our support',
    faqEmpty: 'No question found',
    faqEmptySub: 'Try with other keywords',
    faqSupportTitle: 'Didn\'t find an answer?',
    faqSupportSub: 'Our team is here to help',
    faqPhone: 'Phone',
    favTitle: 'My Favorites',
    favAll: 'All',
    favPharmacies: 'Pharmacies',
    favHospitals: 'Hospitals',
    favDirections: 'Directions',
    favEmpty: 'No favorites',
    favEmptySub: 'Add pharmacies or hospitals to your favorites',
    fpTitle: 'Forgot password?',
    fpDesc1: 'Enter your email or phone number,',
    fpDesc2: 'we will send you a confirmation code',
    fpTabPhone: 'Phone',
    fpEmailPlaceholder: 'example@email.com',
    fpPhonePlaceholder: '0612345678',
    fpResetBtn: 'Reset password',
    fpErrEmail: 'Please enter a valid email',
    fpErrPhone: 'Please enter a valid phone number',
    hiTitle: 'Health & Prevention',
    hiHeroTitle: 'Early protection for your family',
    hiHeroDesc: 'Discover our tips and guides to keep your family healthy',
    hiTopicsTitle: 'Health topics',
    hiTipsTitle: 'Quick tips',
    hiEmergencyTitle: 'Medical emergency?',
    hiEmergencyDesc: 'Immediately contact emergency services',
    hiEmergencyBtn: 'Call',
    hiVaccination: 'Vaccination',
    hiVaccinationDesc: 'Vaccination schedule and important reminders',
    hiPrevention: 'Prevention',
    hiPreventionDesc: 'Tips to prevent diseases',
    hiNutrition: 'Nutrition',
    hiNutritionDesc: 'Food guide for the whole family',
    hiPediatrics: 'Pediatrics',
    hiPediatricsDesc: 'Health monitoring for your children',
    hiFitness: 'Physical Activity',
    hiFitnessDesc: 'Exercises and recommendations',
    hiHydration: 'Hydration',
    hiHydrationDesc: 'Importance of drinking enough water',
    hiTip1Title: 'Wash your hands regularly',
    hiTip1: 'For at least 20 seconds with soap',
    hiTip2Title: 'Sleep enough',
    hiTip2: '7-9 hours for adults, more for children',
    hiTip3Title: 'Eat balanced',
    hiTip3: 'At least 5 fruits and vegetables per day',
    hiTip4Title: 'Stay active',
    hiTip4: 'At least 30 minutes of physical activity per day',
  },
  es: {
    home: 'Inicio',
    profile: 'Perfil',
    appointments: 'Citas',
    notifications: 'Notificaciones',
    favorites: 'Favoritos',
    editProfile: 'Editar perfil',
    language: 'Idioma',
    theme: 'Apariencia',
    prescriptions: 'Mis recetas',
    paymentMethod: 'Método de pago',
    faqs: 'Preguntas frecuentes',
    logout: 'Cerrar sesión',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    success: 'Éxito',
    error: 'Error',
    loading: 'Cargando...',
    profileUpdated: '¡Tu perfil ha sido actualizado con éxito!',
    languageChanged: 'Idioma cambiado a',
    themeChanged: 'Tema cambiado con éxito',
    firstName: 'Nombre',
    lastName: 'Apellido',
    email: 'Correo',
    phone: 'Teléfono',
    address: 'Dirección',
    city: 'Ciudad',
    dateOfBirth: 'Fecha de nacimiento',
    gender: 'Género',
    bloodGroup: 'Grupo sanguíneo',
    height: 'Altura (m)',
    weight: 'Peso (kg)',
    male: 'Hombre',
    female: 'Mujer',
    other: 'Otro',
    areYouSureLogout: '¿Estás seguro de que quieres cerrar sesión?',
    healthInfo: 'Información de salud',
    bloodType: 'Tipo de sangre',
    age: 'Edad',
    bmi: 'Estado IMC',
    rdvCount: 'Citas',
    noNotification: 'Sin notificaciones',
    noNotificationSub: 'Aún no has recibido ninguna notificación.',
    markAllRead: 'Marcar todo como leído',
    bestDoctors: 'Mejores Doctores',
    seeAll: 'Ver todo',
    searchPlaceholder: 'Buscar médico, medicamentos...',
    doctor: 'Doctor',
    pharmacy: 'Farmacia',
    hospital: 'Hospital',
    ambulance: 'Ambulancia',
    bannerTitle1: 'Protección temprana para',
    bannerTitle2: 'la salud de tu familia',
    learnMore: 'Saber más',
    loadingDoctors: 'Cargando médicos...',
    retryButton: 'Reintentar',
    noDoctors: 'No hay médicos disponibles',
    cannotLoadDoctors: 'No se pueden cargar los médicos',
    aptTitle: 'Citas',
    aptLoading: 'Cargando sus citas...',
    aptPending: 'Pendiente',
    aptConfirmed: 'Confirmada',
    aptPast: 'Pasada',
    aptRejected: 'Rechazada',
    aptOnline: 'En línea',
    aptHome: 'A domicilio',
    aptHospital: 'Hospital',
    aptMoreDetails: 'Más detalles',
    aptHideDetails: 'Ocultar detalles',
    aptCall: 'Llamar',
    aptWhatsApp: 'WhatsApp',
    aptDirections: 'Ruta',
    aptJoinVideo: 'Unirse a la consulta',
    aptConfirmedMsg: 'Cita confirmada',
    aptReschedule: 'Reprogramar',
    aptDelete: 'Eliminar',
    aptEmpty: 'Sin citas',
    aptCancelTitle: 'Cancelar cita',
    aptCancelMsg: '¿Está seguro de que desea cancelar esta cita?',
    aptDeleteTitle: 'Eliminar cita',
    aptDeleteMsg: '¿Está seguro de que desea eliminar esta cita?',
    aptCancelSuccess: 'Cita cancelada con éxito',
    aptJoinTitle: 'Unirse a la consulta',
    aptJoinMsg: 'Será redirigido a la videoconferencia',
    aptJoin: 'Unirse',
    aptErrLoad: 'No se pueden cargar sus citas. Inténtelo de nuevo.',
    bkTitle: 'Nueva cita',
    bkTypeTitle: 'Tipo de consulta',
    bkTypeSubtitle: 'Elija el tipo de consulta que más le convenga',
    bkOnline: 'Consulta en línea',
    bkOnlineDesc: 'Consulta por video',
    bkHome: 'Consulta a domicilio',
    bkHomeDesc: 'El médico viene a usted',
    bkHospital: 'Consulta en hospital',
    bkHospitalDesc: 'Cita presencial',
    bkDescLabel: 'Descripción del problema',
    bkDescPlaceholder: 'Describa brevemente su problema de salud...',
    bkNext: 'Siguiente',
    bkValidationMsg: 'Seleccione un tipo y agregue una descripción',
    cpTitle: 'Cambiar contraseña',
    cpInfo: 'Su contraseña debe tener al menos 8 caracteres',
    cpCurrent: 'Contraseña actual',
    cpCurrentPlaceholder: 'Ingrese su contraseña actual',
    cpNew: 'Nueva contraseña',
    cpNewPlaceholder: 'Ingrese su nueva contraseña',
    cpConfirm: 'Confirmar nueva contraseña',
    cpConfirmPlaceholder: 'Confirme su nueva contraseña',
    cpForgot: '¿Olvidó su contraseña?',
    cpWeak: 'Débil',
    cpMedium: 'Medio',
    cpStrong: 'Fuerte',
    cpMatch: 'Las contraseñas coinciden',
    cpNoMatch: 'Las contraseñas no coinciden',
    cpSave: 'Actualizar contraseña',
    cpSuccess: 'Su contraseña ha sido cambiada con éxito',
    cpErrCurrent: 'Ingrese su contraseña actual',
    cpErrNew: 'Ingrese una nueva contraseña',
    cpErrLen: 'La contraseña debe tener al menos 8 caracteres',
    cpErrSame: 'La nueva contraseña debe ser diferente a la anterior',
    cnpTitle: 'Crear nueva contraseña',
    cnpDesc: 'Cree su nueva contraseña para iniciar sesión',
    cnpNew: 'Nueva contraseña',
    cnpConfirm: 'Confirmar contraseña',
    cnpCreate: 'Crear contraseña',
    cnpSuccess: 'Ha restablecido su contraseña con éxito.',
    cnpErrLen: 'La contraseña debe tener al menos 6 caracteres',
    cnpErrMatch: 'Las contraseñas no coinciden',
    cnpLogin: 'Iniciar sesión',
    ddTitle: 'Detalles del médico',
    ddLoading: 'Cargando...',
    ddRetry: 'Reintentar',
    ddAbout: 'Acerca de',
    ddExperience: 'años de experiencia',
    ddPatients: 'pacientes',
    ddDiplomas: 'Diplomas',
    ddPrices: 'Tarifas',
    ddAvailableDates: 'Fechas disponibles',
    ddLoadingDates: 'Cargando disponibilidad...',
    ddNoDates: 'Sin disponibilidad en los próximos 30 días',
    ddAvailableSlots: 'Horarios disponibles',
    ddNoSlots: 'Sin horarios disponibles para esta fecha',
    ddOccupied: 'ocupado',
    ddFeeDetails: 'Detalles de tarifas',
    ddConsultation: 'Consulta',
    ddConfirmFee: 'Tarifa de confirmación',
    ddTotal: 'Total',
    ddNbOnline: 'La tarifa de confirmación de',
    ddNbOnline2: 'FCFA no es reembolsable.',
    ddNbOnlineLabel: 'Nota:',
    ddPayOnSite: 'Pago en sitio:',
    ddPayOnSiteMsg: 'El pago se realizará directamente en la consulta.',
    ddSelectDate: 'Por favor seleccione una fecha',
    ddSelectSlot: 'Por favor seleccione un horario',
    ddContinuePayment: 'Continuar al pago',
    ddConfirmRdv: 'Confirmar cita',
    ddSuccessMsg: '¡Su cita ha sido creada con éxito!',
    ddConsultOnline: 'Consulta en línea',
    ddConsultHome: 'Consulta a domicilio',
    ddConsultHospital: 'Consulta en hospital',
    ddCannotLoad: 'No se pueden cargar los detalles del médico',
    dlTitle: 'Elegir médico',
    dlSearchPlaceholder: 'Buscar un médico...',
    dlLoading: 'Cargando médicos...',
    dlNoDoctor: 'No se encontraron médicos',
    dlTryOther: 'Intente otra búsqueda',
    dlNoneForType: 'Sin médicos disponibles para',
    dlRetry: 'Reintentar',
    dlCannotLoad: 'No se pueden cargar los médicos',
    epTitle: 'Editar Perfil',
    epChangePhoto: 'Cambiar foto',
    epUploading: 'Subiendo...',
    epSave: 'Guardar cambios',
    epDateBirth: 'Fecha de Nacimiento',
    epDatePlaceholder: 'DD/MM/AAAA',
    epGender: 'Género',
    epMale: 'Hombre',
    epFemale: 'Mujer',
    epOther: 'Otro',
    epBloodGroup: 'Grupo Sanguíneo',
    epBloodSelect: 'Seleccionar',
    epHeight: 'Talla (m)',
    epWeight: 'Peso (kg)',
    epPhotoOptions: 'Foto de perfil',
    epTakePhoto: 'Tomar una foto',
    epGallery: 'Elegir de galería',
    epDeletePhoto: 'Eliminar foto',
    epConfirmDate: 'Confirmar',
    epBirthTitle: 'Fecha de nacimiento',
    epBloodTitle: 'Grupo sanguíneo',
    epErrLoad: 'No se puede cargar el perfil.',
    epErrSave: 'Error al guardar.',
    epErrPhoto: 'No se puede subir la foto.',
    epPhotoUpdated: 'Foto actualizada con éxito',
    epDeleteConfirmTitle: 'Eliminar foto',
    epDeleteConfirmMsg: '¿Realmente desea eliminar su foto de perfil?',
    epErrPermissions: 'Permita el acceso a la cámara y galería.',
    epPermTitle: 'Permisos requeridos',
    emTitle: 'Emergencias',
    emMedTitle: 'Emergencia Médica',
    emDesc: 'En caso de emergencia médica, presione el botón para contactar inmediatamente los servicios de emergencia.',
    emCallBtn: 'Llamar Emergencias',
    em24h: 'Este servicio está disponible 24/7',
    emWarning: 'Use este servicio solo en una emergencia real',
    emCallTitle: 'Llamada de emergencia',
    emCallMsg: '¿Desea llamar al',
    emCallAction: 'Llamar',
    emCallError: 'No se puede realizar la llamada',
    faqTitle: 'Preguntas Frecuentes',
    faqSearchPlaceholder: 'Buscar una pregunta...',
    faqCatAll: 'Todos',
    faqCatAccount: 'Cuenta',
    faqCatAppointments: 'Citas',
    faqCatPayment: 'Pago',
    faqCatTechnical: 'Técnico',
    faqBannerTitle: '¿Necesita ayuda?',
    faqBannerText: 'Consulte nuestras preguntas frecuentes o contacte soporte',
    faqEmpty: 'No se encontraron preguntas',
    faqEmptySub: 'Intente con otras palabras clave',
    faqSupportTitle: '¿No encontró respuesta?',
    faqSupportSub: 'Nuestro equipo está aquí para ayudar',
    faqPhone: 'Teléfono',
    favTitle: 'Mis Favoritos',
    favAll: 'Todos',
    favPharmacies: 'Farmacias',
    favHospitals: 'Hospitales',
    favDirections: 'Ruta',
    favEmpty: 'Sin favoritos',
    favEmptySub: 'Agregue farmacias u hospitales a sus favoritos',
    fpTitle: '¿Olvidó su contraseña?',
    fpDesc1: 'Ingrese su email o número de teléfono,',
    fpDesc2: 'le enviaremos un código de confirmación',
    fpTabPhone: 'Teléfono',
    fpEmailPlaceholder: 'ejemplo@email.com',
    fpPhonePlaceholder: '0612345678',
    fpResetBtn: 'Restablecer contraseña',
    fpErrEmail: 'Por favor ingrese un email válido',
    fpErrPhone: 'Por favor ingrese un número de teléfono válido',
    hiTitle: 'Salud y Prevención',
    hiHeroTitle: 'Protección temprana para su familia',
    hiHeroDesc: 'Descubra nuestros consejos y guías para mantener a su familia saludable',
    hiTopicsTitle: 'Temas de salud',
    hiTipsTitle: 'Consejos rápidos',
    hiEmergencyTitle: '¿Emergencia médica?',
    hiEmergencyDesc: 'Contacte inmediatamente los servicios de emergencia',
    hiEmergencyBtn: 'Llamar',
    hiVaccination: 'Vacunación',
    hiVaccinationDesc: 'Calendario de vacunas y recordatorios',
    hiPrevention: 'Prevención',
    hiPreventionDesc: 'Consejos para prevenir enfermedades',
    hiNutrition: 'Nutrición',
    hiNutritionDesc: 'Guía alimentaria para toda la familia',
    hiPediatrics: 'Pediatría',
    hiPediatricsDesc: 'Seguimiento de salud para sus hijos',
    hiFitness: 'Actividad Física',
    hiFitnessDesc: 'Ejercicios y recomendaciones',
    hiHydration: 'Hidratación',
    hiHydrationDesc: 'Importancia de beber suficiente agua',
    hiTip1Title: 'Lávese las manos regularmente',
    hiTip1: 'Al menos 20 segundos con jabón',
    hiTip2Title: 'Duerma suficiente',
    hiTip2: '7-9 horas para adultos, más para niños',
    hiTip3Title: 'Coma equilibrado',
    hiTip3: 'Mínimo 5 frutas y verduras por día',
    hiTip4Title: 'Manténgase activo',
    hiTip4: 'Al menos 30 minutos de actividad física al día',
  },
  de: {
    home: 'Startseite',
    profile: 'Profil',
    appointments: 'Termine',
    notifications: 'Benachrichtigungen',
    favorites: 'Favoriten',
    editProfile: 'Profil bearbeiten',
    language: 'Sprache',
    theme: 'Erscheinungsbild',
    prescriptions: 'Meine Rezepte',
    paymentMethod: 'Zahlungsmethode',
    faqs: 'FAQ',
    logout: 'Abmelden',
    save: 'Speichern',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
    success: 'Erfolg',
    error: 'Fehler',
    loading: 'Laden...',
    profileUpdated: 'Ihr Profil wurde erfolgreich aktualisiert!',
    languageChanged: 'Sprache geändert zu',
    themeChanged: 'Thema erfolgreich geändert',
    firstName: 'Vorname',
    lastName: 'Nachname',
    email: 'E-Mail',
    phone: 'Telefon',
    address: 'Adresse',
    city: 'Stadt',
    dateOfBirth: 'Geburtsdatum',
    gender: 'Geschlecht',
    bloodGroup: 'Blutgruppe',
    height: 'Größe (m)',
    weight: 'Gewicht (kg)',
    male: 'Mann',
    female: 'Frau',
    other: 'Sonstiges',
    areYouSureLogout: 'Möchten Sie sich wirklich abmelden?',
    healthInfo: 'Gesundheitsinformationen',
    bloodType: 'Blutgruppe',
    age: 'Alter',
    bmi: 'BMI-Status',
    rdvCount: 'Termine',
    noNotification: 'Keine Benachrichtigungen',
    noNotificationSub: 'Sie haben noch keine Benachrichtigung erhalten.',
    markAllRead: 'Alle gelesen markieren',
    bestDoctors: 'Beste Ärzte',
    seeAll: 'Alle sehen',
    searchPlaceholder: 'Arzt, Medikamente suchen...',
    doctor: 'Arzt',
    pharmacy: 'Apotheke',
    hospital: 'Krankenhaus',
    ambulance: 'Krankenwagen',
    bannerTitle1: 'Früher Schutz für',
    bannerTitle2: 'die Gesundheit Ihrer Familie',
    learnMore: 'Mehr erfahren',
    loadingDoctors: 'Ärzte werden geladen...',
    retryButton: 'Erneut versuchen',
    noDoctors: 'Keine Ärzte verfügbar',
    cannotLoadDoctors: 'Ärzte konnten nicht geladen werden',
    aptTitle: 'Termine',
    aptLoading: 'Ihre Termine werden geladen...',
    aptPending: 'Ausstehend',
    aptConfirmed: 'Bestätigt',
    aptPast: 'Vergangen',
    aptRejected: 'Abgelehnt',
    aptOnline: 'Online',
    aptHome: 'Hausbesuch',
    aptHospital: 'Krankenhaus',
    aptMoreDetails: 'Mehr Details',
    aptHideDetails: 'Details ausblenden',
    aptCall: 'Anrufen',
    aptWhatsApp: 'WhatsApp',
    aptDirections: 'Route',
    aptJoinVideo: 'Konsultation beitreten',
    aptConfirmedMsg: 'Termin bestätigt',
    aptReschedule: 'Neu planen',
    aptDelete: 'Löschen',
    aptEmpty: 'Keine Termine',
    aptCancelTitle: 'Termin absagen',
    aptCancelMsg: 'Möchten Sie diesen Termin wirklich absagen?',
    aptDeleteTitle: 'Termin löschen',
    aptDeleteMsg: 'Möchten Sie diesen Termin wirklich löschen?',
    aptCancelSuccess: 'Termin erfolgreich abgesagt',
    aptJoinTitle: 'Konsultation beitreten',
    aptJoinMsg: 'Sie werden zur Videokonferenz weitergeleitet',
    aptJoin: 'Beitreten',
    aptErrLoad: 'Termine können nicht geladen werden. Bitte versuchen Sie es erneut.',
    bkTitle: 'Neuer Termin',
    bkTypeTitle: 'Konsultationstyp',
    bkTypeSubtitle: 'Wählen Sie den für Sie passenden Konsultationstyp',
    bkOnline: 'Online-Konsultation',
    bkOnlineDesc: 'Video-Konsultation',
    bkHome: 'Hausbesuch',
    bkHomeDesc: 'Der Arzt kommt zu Ihnen',
    bkHospital: 'Krankenhausbesuch',
    bkHospitalDesc: 'Persönlicher Termin',
    bkDescLabel: 'Problembeschreibung',
    bkDescPlaceholder: 'Beschreiben Sie kurz Ihr Gesundheitsproblem...',
    bkNext: 'Weiter',
    bkValidationMsg: 'Bitte wählen Sie einen Typ und fügen Sie eine Beschreibung hinzu',
    cpTitle: 'Passwort ändern',
    cpInfo: 'Ihr Passwort muss mindestens 8 Zeichen enthalten',
    cpCurrent: 'Aktuelles Passwort',
    cpCurrentPlaceholder: 'Geben Sie Ihr aktuelles Passwort ein',
    cpNew: 'Neues Passwort',
    cpNewPlaceholder: 'Geben Sie Ihr neues Passwort ein',
    cpConfirm: 'Neues Passwort bestätigen',
    cpConfirmPlaceholder: 'Bestätigen Sie Ihr neues Passwort',
    cpForgot: 'Passwort vergessen?',
    cpWeak: 'Schwach',
    cpMedium: 'Mittel',
    cpStrong: 'Stark',
    cpMatch: 'Passwörter stimmen überein',
    cpNoMatch: 'Passwörter stimmen nicht überein',
    cpSave: 'Passwort aktualisieren',
    cpSuccess: 'Ihr Passwort wurde erfolgreich geändert',
    cpErrCurrent: 'Bitte geben Sie Ihr aktuelles Passwort ein',
    cpErrNew: 'Bitte geben Sie ein neues Passwort ein',
    cpErrLen: 'Passwort muss mindestens 8 Zeichen enthalten',
    cpErrSame: 'Das neue Passwort muss sich vom alten unterscheiden',
    cnpTitle: 'Neues Passwort erstellen',
    cnpDesc: 'Erstellen Sie Ihr neues Passwort zum Einloggen',
    cnpNew: 'Neues Passwort',
    cnpConfirm: 'Passwort bestätigen',
    cnpCreate: 'Passwort erstellen',
    cnpSuccess: 'Sie haben Ihr Passwort erfolgreich zurückgesetzt.',
    cnpErrLen: 'Passwort muss mindestens 6 Zeichen enthalten',
    cnpErrMatch: 'Passwörter stimmen nicht überein',
    cnpLogin: 'Anmelden',
    ddTitle: 'Arztdetails',
    ddLoading: 'Laden...',
    ddRetry: 'Erneut versuchen',
    ddAbout: 'Über',
    ddExperience: 'Jahre Erfahrung',
    ddPatients: 'Patienten',
    ddDiplomas: 'Diplome',
    ddPrices: 'Preise',
    ddAvailableDates: 'Verfügbare Daten',
    ddLoadingDates: 'Verfügbarkeit wird geladen...',
    ddNoDates: 'Keine Verfügbarkeit in den nächsten 30 Tagen',
    ddAvailableSlots: 'Verfügbare Slots',
    ddNoSlots: 'Keine Slots für dieses Datum verfügbar',
    ddOccupied: 'besetzt',
    ddFeeDetails: 'Gebührendetails',
    ddConsultation: 'Konsultation',
    ddConfirmFee: 'Bestätigungsgebühr',
    ddTotal: 'Gesamt',
    ddNbOnline: 'Die Bestätigungsgebühr von',
    ddNbOnline2: 'FCFA ist nicht erstattungsfähig.',
    ddNbOnlineLabel: 'Hinweis:',
    ddPayOnSite: 'Zahlung vor Ort:',
    ddPayOnSiteMsg: 'Die Zahlung erfolgt direkt bei der Konsultation.',
    ddSelectDate: 'Bitte wählen Sie ein Datum',
    ddSelectSlot: 'Bitte wählen Sie einen Zeitslot',
    ddContinuePayment: 'Weiter zur Zahlung',
    ddConfirmRdv: 'Termin bestätigen',
    ddSuccessMsg: 'Ihr Termin wurde erfolgreich erstellt!',
    ddConsultOnline: 'Online-Konsultation',
    ddConsultHome: 'Hausbesuch',
    ddConsultHospital: 'Krankenhausbesuch',
    ddCannotLoad: 'Arztdetails konnten nicht geladen werden',
    dlTitle: 'Arzt wählen',
    dlSearchPlaceholder: 'Arzt suchen...',
    dlLoading: 'Ärzte werden geladen...',
    dlNoDoctor: 'Keine Ärzte gefunden',
    dlTryOther: 'Versuchen Sie eine andere Suche',
    dlNoneForType: 'Keine Ärzte verfügbar für',
    dlRetry: 'Erneut versuchen',
    dlCannotLoad: 'Ärzte konnten nicht geladen werden',
    epTitle: 'Profil bearbeiten',
    epChangePhoto: 'Foto ändern',
    epUploading: 'Wird hochgeladen...',
    epSave: 'Änderungen speichern',
    epDateBirth: 'Geburtsdatum',
    epDatePlaceholder: 'TT/MM/JJJJ',
    epGender: 'Geschlecht',
    epMale: 'Männlich',
    epFemale: 'Weiblich',
    epOther: 'Sonstiges',
    epBloodGroup: 'Blutgruppe',
    epBloodSelect: 'Auswählen',
    epHeight: 'Größe (m)',
    epWeight: 'Gewicht (kg)',
    epPhotoOptions: 'Profilfoto',
    epTakePhoto: 'Foto aufnehmen',
    epGallery: 'Aus Galerie wählen',
    epDeletePhoto: 'Foto löschen',
    epConfirmDate: 'Bestätigen',
    epBirthTitle: 'Geburtsdatum',
    epBloodTitle: 'Blutgruppe',
    epErrLoad: 'Profil konnte nicht geladen werden.',
    epErrSave: 'Fehler beim Speichern.',
    epErrPhoto: 'Foto konnte nicht hochgeladen werden.',
    epPhotoUpdated: 'Foto erfolgreich aktualisiert',
    epDeleteConfirmTitle: 'Foto löschen',
    epDeleteConfirmMsg: 'Möchten Sie Ihr Profilfoto wirklich löschen?',
    epErrPermissions: 'Bitte erlauben Sie den Zugriff auf Kamera und Galerie.',
    epPermTitle: 'Berechtigungen erforderlich',
    emTitle: 'Notfall',
    emMedTitle: 'Medizinischer Notfall',
    emDesc: 'Im Notfall drücken Sie die Taste, um sofort die Notfalldienste zu kontaktieren.',
    emCallBtn: 'Notfall anrufen',
    em24h: 'Dieser Dienst ist 24/7 verfügbar',
    emWarning: 'Nutzen Sie diesen Dienst nur im echten Notfall',
    emCallTitle: 'Notfallruf',
    emCallMsg: 'Möchten Sie anrufen',
    emCallAction: 'Anrufen',
    emCallError: 'Anruf nicht möglich',
    faqTitle: 'Häufige Fragen',
    faqSearchPlaceholder: 'Eine Frage suchen...',
    faqCatAll: 'Alle',
    faqCatAccount: 'Konto',
    faqCatAppointments: 'Termine',
    faqCatPayment: 'Zahlung',
    faqCatTechnical: 'Technisch',
    faqBannerTitle: 'Brauchen Sie Hilfe?',
    faqBannerText: 'Durchsuchen Sie unsere FAQ oder kontaktieren Sie den Support',
    faqEmpty: 'Keine Frage gefunden',
    faqEmptySub: 'Versuchen Sie andere Stichwörter',
    faqSupportTitle: 'Keine Antwort gefunden?',
    faqSupportSub: 'Unser Team hilft Ihnen gerne',
    faqPhone: 'Telefon',
    favTitle: 'Meine Favoriten',
    favAll: 'Alle',
    favPharmacies: 'Apotheken',
    favHospitals: 'Krankenhäuser',
    favDirections: 'Route',
    favEmpty: 'Keine Favoriten',
    favEmptySub: 'Fügen Sie Apotheken oder Krankenhäuser zu Ihren Favoriten hinzu',
    fpTitle: 'Passwort vergessen?',
    fpDesc1: 'Geben Sie Ihre E-Mail oder Telefonnummer ein,',
    fpDesc2: 'wir senden Ihnen einen Bestätigungscode',
    fpTabPhone: 'Telefon',
    fpEmailPlaceholder: 'beispiel@email.com',
    fpPhonePlaceholder: '0612345678',
    fpResetBtn: 'Passwort zurücksetzen',
    fpErrEmail: 'Bitte geben Sie eine gültige E-Mail ein',
    fpErrPhone: 'Bitte geben Sie eine gültige Telefonnummer ein',
    hiTitle: 'Gesundheit & Prävention',
    hiHeroTitle: 'Früher Schutz für Ihre Familie',
    hiHeroDesc: 'Entdecken Sie unsere Tipps und Leitfäden für eine gesunde Familie',
    hiTopicsTitle: 'Gesundheitsthemen',
    hiTipsTitle: 'Schnelle Tipps',
    hiEmergencyTitle: 'Medizinischer Notfall?',
    hiEmergencyDesc: 'Kontaktieren Sie sofort die Notfalldienste',
    hiEmergencyBtn: 'Anrufen',
    hiVaccination: 'Impfung',
    hiVaccinationDesc: 'Impfplan und wichtige Erinnerungen',
    hiPrevention: 'Prävention',
    hiPreventionDesc: 'Tipps zur Krankheitsprävention',
    hiNutrition: 'Ernährung',
    hiNutritionDesc: 'Ernährungsleitfaden für die ganze Familie',
    hiPediatrics: 'Pädiatrie',
    hiPediatricsDesc: 'Gesundheitsüberwachung für Ihre Kinder',
    hiFitness: 'Körperliche Aktivität',
    hiFitnessDesc: 'Übungen und Empfehlungen',
    hiHydration: 'Hydration',
    hiHydrationDesc: 'Bedeutung des ausreichenden Trinkens',
    hiTip1Title: 'Waschen Sie regelmäßig Ihre Hände',
    hiTip1: 'Mindestens 20 Sekunden mit Seife',
    hiTip2Title: 'Schlafen Sie genug',
    hiTip2: '7-9 Stunden für Erwachsene, mehr für Kinder',
    hiTip3Title: 'Essen Sie ausgewogen',
    hiTip3: 'Mindestens 5 Obst und Gemüse pro Tag',
    hiTip4Title: 'Bleiben Sie aktiv',
    hiTip4: 'Mindestens 30 Minuten körperliche Aktivität täglich',
  },
  ar: {
    home: 'الرئيسية',
    profile: 'الملف الشخصي',
    appointments: 'المواعيد',
    notifications: 'الإشعارات',
    favorites: 'المفضلة',
    editProfile: 'تعديل الملف الشخصي',
    language: 'اللغة',
    theme: 'المظهر',
    prescriptions: 'وصفاتي الطبية',
    paymentMethod: 'طريقة الدفع',
    faqs: 'الأسئلة الشائعة',
    logout: 'تسجيل الخروج',
    save: 'حفظ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    success: 'نجاح',
    error: 'خطأ',
    loading: 'جارٍ التحميل...',
    profileUpdated: 'تم تحديث ملفك الشخصي بنجاح!',
    languageChanged: 'تم تغيير اللغة إلى',
    themeChanged: 'تم تغيير السمة بنجاح',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    address: 'العنوان',
    city: 'المدينة',
    dateOfBirth: 'تاريخ الميلاد',
    gender: 'الجنس',
    bloodGroup: 'فصيلة الدم',
    height: 'الطول (م)',
    weight: 'الوزن (كغ)',
    male: 'ذكر',
    female: 'أنثى',
    other: 'آخر',
    areYouSureLogout: 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    healthInfo: 'معلومات صحية',
    bloodType: 'فصيلة الدم',
    age: 'العمر',
    bmi: 'حالة مؤشر كتلة الجسم',
    rdvCount: 'المواعيد',
    noNotification: 'لا توجد إشعارات',
    noNotificationSub: 'لم تتلق أي إشعار بعد.',
    markAllRead: 'تعليم الكل كمقروء',
    bestDoctors: 'أفضل الأطباء',
    seeAll: 'عرض الكل',
    searchPlaceholder: 'ابحث عن طبيب، أدوية...',
    doctor: 'طبيب',
    pharmacy: 'صيدلية',
    hospital: 'مستشفى',
    ambulance: 'إسعاف',
    bannerTitle1: 'حماية مبكرة',
    bannerTitle2: 'لصحة عائلتك',
    learnMore: 'اعرف المزيد',
    loadingDoctors: 'جارٍ تحميل الأطباء...',
    retryButton: 'إعادة المحاولة',
    noDoctors: 'لا يوجد أطباء متاحون',
    cannotLoadDoctors: 'تعذر تحميل الأطباء',
    aptTitle: 'المواعيد',
    aptLoading: 'جارٍ تحميل مواعيدك...',
    aptPending: 'قيد الانتظار',
    aptConfirmed: 'مؤكد',
    aptPast: 'منتهي',
    aptRejected: 'مرفوض',
    aptOnline: 'عبر الإنترنت',
    aptHome: 'في المنزل',
    aptHospital: 'في المستشفى',
    aptMoreDetails: 'مزيد من التفاصيل',
    aptHideDetails: 'إخفاء التفاصيل',
    aptCall: 'اتصال',
    aptWhatsApp: 'واتساب',
    aptDirections: 'الاتجاهات',
    aptJoinVideo: 'الانضمام للاستشارة',
    aptConfirmedMsg: 'الموعد مؤكد',
    aptReschedule: 'إعادة جدولة',
    aptDelete: 'حذف',
    aptEmpty: 'لا توجد مواعيد',
    aptCancelTitle: 'إلغاء الموعد',
    aptCancelMsg: 'هل أنت متأكد أنك تريد إلغاء هذا الموعد؟',
    aptDeleteTitle: 'حذف الموعد',
    aptDeleteMsg: 'هل أنت متأكد أنك تريد حذف هذا الموعد؟',
    aptCancelSuccess: 'تم إلغاء الموعد بنجاح',
    aptJoinTitle: 'الانضمام للاستشارة',
    aptJoinMsg: 'سيتم توجيهك إلى مؤتمر الفيديو',
    aptJoin: 'انضمام',
    aptErrLoad: 'تعذر تحميل مواعيدك. يرجى المحاولة مرة أخرى.',
    bkTitle: 'موعد جديد',
    bkTypeTitle: 'نوع الاستشارة',
    bkTypeSubtitle: 'اختر نوع الاستشارة المناسب لك',
    bkOnline: 'استشارة عبر الإنترنت',
    bkOnlineDesc: 'استشارة بالفيديو',
    bkHome: 'استشارة في المنزل',
    bkHomeDesc: 'الطبيب يأتي إليك',
    bkHospital: 'استشارة في المستشفى',
    bkHospitalDesc: 'موعد حضوري',
    bkDescLabel: 'وصف المشكلة',
    bkDescPlaceholder: 'صف مشكلتك الصحية باختصار...',
    bkNext: 'التالي',
    bkValidationMsg: 'الرجاء اختيار النوع وإضافة وصف',
    cpTitle: 'تغيير كلمة المرور',
    cpInfo: 'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل',
    cpCurrent: 'كلمة المرور الحالية',
    cpCurrentPlaceholder: 'أدخل كلمة مرورك الحالية',
    cpNew: 'كلمة المرور الجديدة',
    cpNewPlaceholder: 'أدخل كلمة مرورك الجديدة',
    cpConfirm: 'تأكيد كلمة المرور الجديدة',
    cpConfirmPlaceholder: 'أكد كلمة مرورك الجديدة',
    cpForgot: 'هل نسيت كلمة المرور؟',
    cpWeak: 'ضعيفة',
    cpMedium: 'متوسطة',
    cpStrong: 'قوية',
    cpMatch: 'كلمات المرور متطابقة',
    cpNoMatch: 'كلمات المرور غير متطابقة',
    cpSave: 'تحديث كلمة المرور',
    cpSuccess: 'تم تغيير كلمة مرورك بنجاح',
    cpErrCurrent: 'الرجاء إدخال كلمة مرورك الحالية',
    cpErrNew: 'الرجاء إدخال كلمة مرور جديدة',
    cpErrLen: 'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل',
    cpErrSame: 'يجب أن تكون كلمة المرور الجديدة مختلفة عن القديمة',
    cnpTitle: 'إنشاء كلمة مرور جديدة',
    cnpDesc: 'أنشئ كلمة مرورك الجديدة لتسجيل الدخول',
    cnpNew: 'كلمة المرور الجديدة',
    cnpConfirm: 'تأكيد كلمة المرور',
    cnpCreate: 'إنشاء كلمة المرور',
    cnpSuccess: 'لقد أعدت تعيين كلمة مرورك بنجاح.',
    cnpErrLen: 'يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل',
    cnpErrMatch: 'كلمات المرور غير متطابقة',
    cnpLogin: 'تسجيل الدخول',
    ddTitle: 'تفاصيل الطبيب',
    ddLoading: 'جارٍ التحميل...',
    ddRetry: 'إعادة المحاولة',
    ddAbout: 'حول',
    ddExperience: 'سنوات خبرة',
    ddPatients: 'مريض',
    ddDiplomas: 'الشهادات',
    ddPrices: 'الأسعار',
    ddAvailableDates: 'التواريخ المتاحة',
    ddLoadingDates: 'جارٍ تحميل التوفر...',
    ddNoDates: 'لا يوجد توفر خلال الـ 30 يومًا القادمة',
    ddAvailableSlots: 'المواعيد المتاحة',
    ddNoSlots: 'لا توجد مواعيد متاحة لهذا التاريخ',
    ddOccupied: 'محجوز',
    ddFeeDetails: 'تفاصيل الرسوم',
    ddConsultation: 'استشارة',
    ddConfirmFee: 'رسوم التأكيد',
    ddTotal: 'المجموع',
    ddNbOnline: 'رسوم التأكيد البالغة',
    ddNbOnline2: 'FCFA غير قابلة للاسترداد.',
    ddNbOnlineLabel: 'ملاحظة:',
    ddPayOnSite: 'الدفع في الموقع:',
    ddPayOnSiteMsg: 'سيتم الدفع مباشرة أثناء الاستشارة.',
    ddSelectDate: 'الرجاء اختيار تاريخ',
    ddSelectSlot: 'الرجاء اختيار موعد',
    ddContinuePayment: 'المتابعة إلى الدفع',
    ddConfirmRdv: 'تأكيد الموعد',
    ddSuccessMsg: 'تم إنشاء موعدك بنجاح!',
    ddConsultOnline: 'استشارة عبر الإنترنت',
    ddConsultHome: 'استشارة منزلية',
    ddConsultHospital: 'استشارة في المستشفى',
    ddCannotLoad: 'تعذر تحميل تفاصيل الطبيب',
    dlTitle: 'اختر طبيبًا',
    dlSearchPlaceholder: 'ابحث عن طبيب...',
    dlLoading: 'جارٍ تحميل الأطباء...',
    dlNoDoctor: 'لم يتم العثور على أطباء',
    dlTryOther: 'جرب بحثًا آخر',
    dlNoneForType: 'لا يوجد أطباء متاحون لـ',
    dlRetry: 'إعادة المحاولة',
    dlCannotLoad: 'تعذر تحميل الأطباء',
    epTitle: 'تعديل الملف الشخصي',
    epChangePhoto: 'تغيير الصورة',
    epUploading: 'جارٍ الرفع...',
    epSave: 'حفظ التغييرات',
    epDateBirth: 'تاريخ الميلاد',
    epDatePlaceholder: 'يي/شش/سسسس',
    epGender: 'الجنس',
    epMale: 'ذكر',
    epFemale: 'أنثى',
    epOther: 'آخر',
    epBloodGroup: 'فصيلة الدم',
    epBloodSelect: 'اختر',
    epHeight: 'الطول (م)',
    epWeight: 'الوزن (كغ)',
    epPhotoOptions: 'صورة الملف الشخصي',
    epTakePhoto: 'التقاط صورة',
    epGallery: 'اختر من المعرض',
    epDeletePhoto: 'حذف الصورة',
    epConfirmDate: 'تأكيد',
    epBirthTitle: 'تاريخ الميلاد',
    epBloodTitle: 'فصيلة الدم',
    epErrLoad: 'تعذر تحميل الملف الشخصي.',
    epErrSave: 'خطأ في الحفظ.',
    epErrPhoto: 'تعذر رفع الصورة.',
    epPhotoUpdated: 'تم تحديث الصورة بنجاح',
    epDeleteConfirmTitle: 'حذف الصورة',
    epDeleteConfirmMsg: 'هل تريد حقًا حذف صورة ملفك الشخصي؟',
    epErrPermissions: 'يرجى السماح بالوصول إلى الكاميرا والمعرض.',
    epPermTitle: 'الأذونات مطلوبة',
    emTitle: 'طوارئ',
    emMedTitle: 'حالة طارئة طبية',
    emDesc: 'في حالة الطوارئ الطبية، اضغط على الزر أدناه للتواصل فورًا مع خدمات الطوارئ.',
    emCallBtn: 'الاتصال بالطوارئ',
    em24h: 'هذه الخدمة متاحة على مدار الساعة 24/7',
    emWarning: 'استخدم هذه الخدمة فقط في حالات الطوارئ الحقيقية',
    emCallTitle: 'مكالمة طارئة',
    emCallMsg: 'هل تريد الاتصال بـ',
    emCallAction: 'اتصال',
    emCallError: 'تعذر إجراء المكالمة',
    faqTitle: 'الأسئلة الشائعة',
    faqSearchPlaceholder: 'ابحث عن سؤال...',
    faqCatAll: 'الكل',
    faqCatAccount: 'الحساب',
    faqCatAppointments: 'المواعيد',
    faqCatPayment: 'الدفع',
    faqCatTechnical: 'تقني',
    faqBannerTitle: 'هل تحتاج مساعدة؟',
    faqBannerText: 'تصفح أسئلتنا الشائعة أو تواصل مع الدعم',
    faqEmpty: 'لم يتم العثور على سؤال',
    faqEmptySub: 'جرب كلمات بحث أخرى',
    faqSupportTitle: 'لم تجد إجابة؟',
    faqSupportSub: 'فريقنا هنا لمساعدتك',
    faqPhone: 'هاتف',
    favTitle: 'المفضلة',
    favAll: 'الكل',
    favPharmacies: 'صيدليات',
    favHospitals: 'مستشفيات',
    favDirections: 'الاتجاهات',
    favEmpty: 'لا توجد مفضلة',
    favEmptySub: 'أضف صيدليات أو مستشفيات إلى مفضلتك',
    fpTitle: 'هل نسيت كلمة المرور؟',
    fpDesc1: 'أدخل بريدك الإلكتروني أو رقم هاتفك،',
    fpDesc2: 'سنرسل لك رمز تأكيد',
    fpTabPhone: 'هاتف',
    fpEmailPlaceholder: 'مثال@email.com',
    fpPhonePlaceholder: '0612345678',
    fpResetBtn: 'إعادة تعيين كلمة المرور',
    fpErrEmail: 'الرجاء إدخال بريد إلكتروني صحيح',
    fpErrPhone: 'الرجاء إدخال رقم هاتف صحيح',
    hiTitle: 'الصحة والوقاية',
    hiHeroTitle: 'حماية مبكرة لعائلتك',
    hiHeroDesc: 'اكتشف نصائحنا وأدلتنا للحفاظ على صحة عائلتك',
    hiTopicsTitle: 'مواضيع صحية',
    hiTipsTitle: 'نصائح سريعة',
    hiEmergencyTitle: 'حالة طارئة طبية؟',
    hiEmergencyDesc: 'اتصل فوراً بخدمات الطوارئ',
    hiEmergencyBtn: 'اتصال',
    hiVaccination: 'التطعيم',
    hiVaccinationDesc: 'جدول التطعيمات والتذكيرات',
    hiPrevention: 'الوقاية',
    hiPreventionDesc: 'نصائح للوقاية من الأمراض',
    hiNutrition: 'التغذية',
    hiNutritionDesc: 'دليل غذائي لكامل العائلة',
    hiPediatrics: 'طب الأطفال',
    hiPediatricsDesc: 'متابعة صحة أطفالك',
    hiFitness: 'النشاط البدني',
    hiFitnessDesc: 'تمارين وتوصيات',
    hiHydration: 'الترطيب',
    hiHydrationDesc: 'أهمية شرب الماء بكميات كافية',
    hiTip1Title: 'اغسل يديك بانتظام',
    hiTip1: 'لمدة 20 ثانية على الأقل بالصابون',
    hiTip2Title: 'نم بما يكفي',
    hiTip2: '7-9 ساعات للبالغين، أكثر للأطفال',
    hiTip3Title: 'تناول طعاماً متوازناً',
    hiTip3: '5 فواكه وخضروات يومياً على الأقل',
    hiTip4Title: 'ابق نشيطاً',
    hiTip4: '30 دقيقة من النشاط البدني يومياً على الأقل',
  },
  zh: {
    home: '首页',
    profile: '个人资料',
    appointments: '预约',
    notifications: '通知',
    favorites: '收藏',
    editProfile: '编辑资料',
    language: '语言',
    theme: '外观',
    prescriptions: '我的处方',
    paymentMethod: '支付方式',
    faqs: '常见问题',
    logout: '退出登录',
    save: '保存',
    cancel: '取消',
    confirm: '确认',
    success: '成功',
    error: '错误',
    loading: '加载中...',
    profileUpdated: '您的资料已成功更新！',
    languageChanged: '语言已更改为',
    themeChanged: '主题已成功更改',
    firstName: '名',
    lastName: '姓',
    email: '邮箱',
    phone: '电话',
    address: '地址',
    city: '城市',
    dateOfBirth: '出生日期',
    gender: '性别',
    bloodGroup: '血型',
    height: '身高（米）',
    weight: '体重（千克）',
    male: '男',
    female: '女',
    other: '其他',
    areYouSureLogout: '您确定要退出登录吗？',
    healthInfo: '健康信息',
    bloodType: '血型',
    age: '年龄',
    bmi: 'BMI状态',
    rdvCount: '预约',
    noNotification: '暂无通知',
    noNotificationSub: '您还没有收到任何通知。',
    markAllRead: '全部标为已读',
    bestDoctors: '最佳医生',
    seeAll: '查看全部',
    searchPlaceholder: '搜索医生、药品...',
    doctor: '医生',
    pharmacy: '药店',
    hospital: '医院',
    ambulance: '救护车',
    bannerTitle1: '早期保护',
    bannerTitle2: '您家人的健康',
    learnMore: '了解更多',
    loadingDoctors: '正在加载医生...',
    retryButton: '重试',
    noDoctors: '暂无医生',
    cannotLoadDoctors: '无法加载医生',
    aptTitle: '预约',
    aptLoading: '正在加载您的预约...',
    aptPending: '待处理',
    aptConfirmed: '已确认',
    aptPast: '已过期',
    aptRejected: '已拒绝',
    aptOnline: '线上',
    aptHome: '上门',
    aptHospital: '医院',
    aptMoreDetails: '更多详情',
    aptHideDetails: '隐藏详情',
    aptCall: '通话',
    aptWhatsApp: 'WhatsApp',
    aptDirections: '导航',
    aptJoinVideo: '加入会诊',
    aptConfirmedMsg: '预约已确认',
    aptReschedule: '重新安排',
    aptDelete: '删除',
    aptEmpty: '暂无预约',
    aptCancelTitle: '取消预约',
    aptCancelMsg: '您确定要取消此预约吗？',
    aptDeleteTitle: '删除预约',
    aptDeleteMsg: '您确定要删除此预约吗？',
    aptCancelSuccess: '预约已成功取消',
    aptJoinTitle: '加入会诊',
    aptJoinMsg: '您将被重定向到视频会议',
    aptJoin: '加入',
    aptErrLoad: '无法加载您的预约，请重试。',
    bkTitle: '新预约',
    bkTypeTitle: '会诊类型',
    bkTypeSubtitle: '选择适合您的会诊类型',
    bkOnline: '线上会诊',
    bkOnlineDesc: '视频会诊',
    bkHome: '上门会诊',
    bkHomeDesc: '医生上门',
    bkHospital: '医院会诊',
    bkHospitalDesc: '面对面预约',
    bkDescLabel: '问题描述',
    bkDescPlaceholder: '简要描述您的健康问题...',
    bkNext: '下一步',
    bkValidationMsg: '请选择类型并添加描述',
    cpTitle: '更改密码',
    cpInfo: '您的密码必须至少包含8个字符',
    cpCurrent: '当前密码',
    cpCurrentPlaceholder: '输入当前密码',
    cpNew: '新密码',
    cpNewPlaceholder: '输入新密码',
    cpConfirm: '确认新密码',
    cpConfirmPlaceholder: '确认新密码',
    cpForgot: '忘记密码？',
    cpWeak: '弱',
    cpMedium: '中',
    cpStrong: '强',
    cpMatch: '密码匹配',
    cpNoMatch: '密码不匹配',
    cpSave: '更新密码',
    cpSuccess: '您的密码已成功更改',
    cpErrCurrent: '请输入当前密码',
    cpErrNew: '请输入新密码',
    cpErrLen: '密码必须至少包含8个字符',
    cpErrSame: '新密码必须与旧密码不同',
    cnpTitle: '创建新密码',
    cnpDesc: '创建您的新密码以登录',
    cnpNew: '新密码',
    cnpConfirm: '确认密码',
    cnpCreate: '创建密码',
    cnpSuccess: '您已成功重置密码。',
    cnpErrLen: '密码必须至少包含6个字符',
    cnpErrMatch: '密码不匹配',
    cnpLogin: '登录',
    ddTitle: '医生详情',
    ddLoading: '加载中...',
    ddRetry: '重试',
    ddAbout: '关于',
    ddExperience: '年经验',
    ddPatients: '名患者',
    ddDiplomas: '文凭',
    ddPrices: '价格',
    ddAvailableDates: '可用日期',
    ddLoadingDates: '正在加载可用时间...',
    ddNoDates: '未来30天内无可用时间',
    ddAvailableSlots: '可用时段',
    ddNoSlots: '该日期无可用时段',
    ddOccupied: '已占用',
    ddFeeDetails: '费用详情',
    ddConsultation: '会诊',
    ddConfirmFee: '确认费',
    ddTotal: '总计',
    ddNbOnline: '确认费',
    ddNbOnline2: 'FCFA 不可退款。',
    ddNbOnlineLabel: '注：',
    ddPayOnSite: '现场付款：',
    ddPayOnSiteMsg: '付款将直接在会诊时进行。',
    ddSelectDate: '请选择日期',
    ddSelectSlot: '请选择时段',
    ddContinuePayment: '继续付款',
    ddConfirmRdv: '确认预约',
    ddSuccessMsg: '您的预约已成功创建！',
    ddConsultOnline: '线上会诊',
    ddConsultHome: '上门会诊',
    ddConsultHospital: '医院会诊',
    ddCannotLoad: '无法加载医生详情',
    dlTitle: '选择医生',
    dlSearchPlaceholder: '搜索医生...',
    dlLoading: '正在加载医生...',
    dlNoDoctor: '未找到医生',
    dlTryOther: '请尝试其他搜索',
    dlNoneForType: '暂无可用医生提供',
    dlRetry: '重试',
    dlCannotLoad: '无法加载医生',
    epTitle: '编辑个人资料',
    epChangePhoto: '更换照片',
    epUploading: '上传中...',
    epSave: '保存更改',
    epDateBirth: '出生日期',
    epDatePlaceholder: '日/月/年',
    epGender: '性别',
    epMale: '男',
    epFemale: '女',
    epOther: '其他',
    epBloodGroup: '血型',
    epBloodSelect: '选择',
    epHeight: '身高 (m)',
    epWeight: '体重 (kg)',
    epPhotoOptions: '头像',
    epTakePhoto: '拍照',
    epGallery: '从相册选择',
    epDeletePhoto: '删除照片',
    epConfirmDate: '确认',
    epBirthTitle: '出生日期',
    epBloodTitle: '血型',
    epErrLoad: '无法加载个人资料。',
    epErrSave: '保存错误。',
    epErrPhoto: '无法上传照片。',
    epPhotoUpdated: '照片更新成功',
    epDeleteConfirmTitle: '删除照片',
    epDeleteConfirmMsg: '您真的要删除您的头像吗？',
    epErrPermissions: '请允许访问相机和相册。',
    epPermTitle: '需要权限',
    emTitle: '紧急',
    emMedTitle: '医疗紧急情况',
    emDesc: '如遇医疗紧急情况，请按下方按钮立即联系急救服务。',
    emCallBtn: '拨打急救',
    em24h: '该服务全天24小时可用',
    emWarning: '仅在真正紧急情况下使用此服务',
    emCallTitle: '紧急呼叫',
    emCallMsg: '您要拨打',
    emCallAction: '拨打',
    emCallError: '无法拨打电话',
    faqTitle: '常见问题',
    faqSearchPlaceholder: '搜索问题...',
    faqCatAll: '全部',
    faqCatAccount: '账户',
    faqCatAppointments: '预约',
    faqCatPayment: '支付',
    faqCatTechnical: '技术',
    faqBannerTitle: '需要帮助？',
    faqBannerText: '浏览我们的常见问题或联系支持',
    faqEmpty: '未找到问题',
    faqEmptySub: '请尝试其他关键词',
    faqSupportTitle: '没有找到答案？',
    faqSupportSub: '我们的团队随时为您提供帮助',
    faqPhone: '电话',
    favTitle: '我的收藏',
    favAll: '全部',
    favPharmacies: '药店',
    favHospitals: '医院',
    favDirections: '导航',
    favEmpty: '暂无收藏',
    favEmptySub: '将药店或医院添加到您的收藏',
    fpTitle: '忘记密码？',
    fpDesc1: '输入您的邮箱或手机号码，',
    fpDesc2: '我们将发送验证码',
    fpTabPhone: '电话',
    fpEmailPlaceholder: '示例@email.com',
    fpPhonePlaceholder: '0612345678',
    fpResetBtn: '重置密码',
    fpErrEmail: '请输入有效的邮箱',
    fpErrPhone: '请输入有效的手机号码',
    hiTitle: '健康与预防',
    hiHeroTitle: '为您的家庭提供早期保护',
    hiHeroDesc: '发现我们的建议和指南，保持家人健康',
    hiTopicsTitle: '健康主题',
    hiTipsTitle: '快速建议',
    hiEmergencyTitle: '医疗紧急情况？',
    hiEmergencyDesc: '立即联系急救服务',
    hiEmergencyBtn: '拨打',
    hiVaccination: '疫苗接种',
    hiVaccinationDesc: '疫苗接种计划和重要提醒',
    hiPrevention: '预防',
    hiPreventionDesc: '疾病预防建议',
    hiNutrition: '营养',
    hiNutritionDesc: '全家饮食指南',
    hiPediatrics: '儿科',
    hiPediatricsDesc: '儿童健康监测',
    hiFitness: '体育锻炼',
    hiFitnessDesc: '锻炼和建议',
    hiHydration: '水分补充',
    hiHydrationDesc: '充足饮水的重要性',
    hiTip1Title: '经常洗手',
    hiTip1: '用肥皂洗至少20秒',
    hiTip2Title: '睡眠充足',
    hiTip2: '成人7-9小时，儿童更多',
    hiTip3Title: '均衡饮食',
    hiTip3: '每天至少5种水果和蔬菜',
    hiTip4Title: '保持活跃',
    hiTip4: '每天至少30分钟体育活动',
  },
};

export const i18n = new I18n(translations);
i18n.enableFallback = true;
i18n.defaultLocale = 'fr';

// ─────────────────────────────────────────────────────────────
// 🏷️ TYPES
// ─────────────────────────────────────────────────────────────
interface User {
  id: number;
  email: string;
  nom: string;
  prenom: string;
}

interface Colors {
  background: string; text: string; subText: string;
  card: string; inputBackground: string; border: string;
}

interface AuthContextType {
  user: User | null;
  isAuthenticated: boolean;
  login: (user: User) => Promise<void>;
  logout: () => Promise<void>;
  updateUser: (user: User) => void;
}

interface AppContextType {
  colors: Colors;
  isDarkMode: boolean;
  toggleTheme: () => void;
  theme: 'light' | 'dark' | 'auto';
  setTheme: (theme: 'light' | 'dark' | 'auto') => Promise<void>;
  language: string;
  setLanguage: (code: string) => Promise<void>;
  t: (key: string) => string;
}

// ─────────────────────────────────────────────────────────────
// 🎨 COULEURS
// ─────────────────────────────────────────────────────────────
const lightColors: Colors = {
  background: '#ffffff', text: '#000000', subText: '#666666',
  card: '#f5f5f5', inputBackground: '#f0f0f0', border: '#e2e8f0',
};
const darkColors: Colors = {
  background: '#1a1a1a', text: '#ffffff', subText: '#b0b0b0',
  card: '#2a2a2a', inputBackground: '#333333', border: '#444444',
};

// ─────────────────────────────────────────────────────────────
// 📦 CONTEXTES
// ─────────────────────────────────────────────────────────────
const AuthContext = createContext<AuthContextType | undefined>(undefined);
const AppContext  = createContext<AppContextType  | undefined>(undefined);

// ─────────────────────────────────────────────────────────────
// 🏗️ PROVIDER UNIQUE
// user/session + thème/langue dans un seul provider
// PAS de key={language} → pas de déconnexion
// La langue s'applique via t() qui lit `language` (state React)
// ─────────────────────────────────────────────────────────────
export const AppProvider = ({ children }: { children: ReactNode }) => {

  // ── Auth ──────────────────────────────────────────────────
  const [user, setUser] = useState<User | null>(null);

  // ── Thème/Langue ──────────────────────────────────────────
  const [theme, setThemeState]       = useState<'light' | 'dark' | 'auto'>('light');
  const [isDarkMode, setIsDarkMode]  = useState(false);
  const [language, setLanguageState] = useState('fr');

  // ── Chargement initial ────────────────────────────────────
  useEffect(() => {
    const load = async () => {
      try {
        const [savedUser, savedTheme, savedLanguage] = await Promise.all([
          AsyncStorage.getItem('user'),
          AsyncStorage.getItem('app_theme'),
          AsyncStorage.getItem('app_language'),
        ]);

        // Session — lecture seule, pas de setState qui déclenche re-mount
        if (savedUser) setUser(JSON.parse(savedUser));

        // Langue
        if (savedLanguage) {
          setLanguageState(savedLanguage);
        } else {
          const deviceLocale = Localization.getLocales?.()?.[0]?.languageCode ?? 'fr';
          const supported    = Object.keys(translations);
          setLanguageState(supported.includes(deviceLocale) ? deviceLocale : 'fr');
        }

        // Thème
        if (savedTheme) {
          setThemeState(savedTheme as 'light' | 'dark' | 'auto');
          setIsDarkMode(savedTheme === 'dark');
        }
      } catch (e) {
        console.error('Erreur chargement préférences:', e);
      }
    };
    load();
  }, []);

  // ── Auth functions ────────────────────────────────────────
  const login = async (userData: User) => {
    await AsyncStorage.setItem('user', JSON.stringify(userData));
    setUser(userData);
  };

  const logout = async () => {
    await AsyncStorage.removeItem('user');
    setUser(null);
  };

  const updateUser = (userData: User) => setUser(userData);

  // ── Thème ─────────────────────────────────────────────────
  const toggleTheme = () => {
    const newDark = !isDarkMode;
    setIsDarkMode(newDark);
    setThemeState(newDark ? 'dark' : 'light');
    AsyncStorage.setItem('app_theme', newDark ? 'dark' : 'light');
  };

  const setTheme = async (newTheme: 'light' | 'dark' | 'auto') => {
    setThemeState(newTheme);
    setIsDarkMode(newTheme === 'dark');
    await AsyncStorage.setItem('app_theme', newTheme);
  };

  // ── Langue ────────────────────────────────────────────────
  const setLanguage = async (code: string) => {
    setLanguageState(code);
    await AsyncStorage.setItem('app_language', code);
  };

  // ── Traduction ────────────────────────────────────────────
  // Lit `language` du state React → re-render automatique de TOUS
  // les composants qui appellent t() quand la langue change
  // SANS re-monter les composants → session préservée ✅
  const t = (key: string): string => {
    try {
      const dict = translations[language as keyof typeof translations] ?? translations['fr'];
      return (dict as any)[key] ?? (translations['fr'] as any)[key] ?? key;
    } catch {
      return key;
    }
  };

  // ── Valeurs ───────────────────────────────────────────────
  const authValue: AuthContextType = {
    user, isAuthenticated: !!user, login, logout, updateUser,
  };

  const appValue: AppContextType = {
    colors: isDarkMode ? darkColors : lightColors,
    isDarkMode, toggleTheme,
    theme, setTheme,
    language, setLanguage,
    t,
  };

  // ── Rendu — PAS de key sur les providers ──────────────────
  // key forcerait un re-mount (destroy + recreate) → déconnexion
  // Le re-render via state suffit pour mettre à jour t()
  return (
    <AuthContext.Provider value={authValue}>
      <AppContext.Provider value={appValue}>
        {children}
      </AppContext.Provider>
    </AuthContext.Provider>
  );
};

// ─────────────────────────────────────────────────────────────
// 🪝 HOOKS
// ─────────────────────────────────────────────────────────────
export const useAuth = () => {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error('useAuth must be used within an AppProvider');
  return ctx;
};

export const useApp = () => {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error('useApp must be used within an AppProvider');
  return ctx;
};